.:
  name: .
  description: 根目录，按照内容与来源分类
健康护理:
  name: 健康护理
  description: 此目录收录了与跨性别者健康护理相关的资源与信息，包括心理支持、手术经验及激素治疗等方面的内容。这些资料旨在帮助跨性别者了解和获取所需的医疗资源，支持他们的过渡过程。
健康护理/其他:
  name: 其他
  description: 该目录包含关于跨性别者在中国的健康护理及相关医疗资源的信息，特别是一些其他类型的支持和资源，不适合进行分类的资料。这些资料旨在帮助跨性别者更好地理解和获取所需的医疗信息与服务。
健康护理/心理:
  name: 心理
  description: 本目录包含关于跨性别者心理健康的研究和经验分享，探讨了心理咨询与积极心理疗法在跨性别群体中的应用，以及与变性手术相关的心理护理内容。
健康护理/手术:
  name: 手术
  description: 本目录包含与跨性别医疗护理和手术相关的资料，涵盖变性手术的流程、临床研究、手术护理及心理护理等内容。通过这些信息，旨在为跨性别者提供必要的手术知识和医疗资源，助力他们的身体过渡与心理适应。
健康护理/激素:
  name: 激素
  description: 该目录收录与跨性别者在激素治疗相关的医疗资源和经验分享，包括各种激素使用的指南、研究、患者故事等。适合希望了解激素治疗过程的跨性别者及其支持者，提供科学数据与真实经历的交融。
文学与艺术作品:
  name: 文学与艺术作品
  description: 此目录收录与跨性别相关的文学及艺术作品，包括小说、诗歌、绘画等，通过艺术表达跨性别者的生活体验和内心世界，展示他们的故事与情感。
新闻:
  name: 新闻
  description: 这个目录包含与跨性别相关的新闻报道和最新动态，旨在提供关于跨性别者的社会关注度、法律变化和重要事件的最新信息。
法律:
  name: 法律
  description: 本目录包含关于办理特殊公证的心得体会，探讨在跨性别法律事务中所遇到的挑战与经验，旨在为其他跨性别者提供参考与帮助。
生活:
  name: 生活
  description: 该目录包含与跨性别者日常生活相关的文档，包括个人欲望、家庭关系以及父母的理解与支持，旨在分享生活中的真实经历与挑战。
生活/RLE:
  name: RLE
  description: 本目录包含跨性别者的变装指导与经验分享，旨在帮助有志于探索自己性别认同的人士，从基础到进阶掌握女装技巧，提供实用的变装手册和声音训练资源。
生活/欲望:
  name: 欲望
  description: 本目录收录了与跨性别相关的欲望主题内容，包括个人对变性后欲望的体验和分享，以及针对跨性别者的特定的身体探索手册，以促进对自身需求和欲望的认知和理解。
生活/父母:
  name: 父母
  description: 本目录旨在为跨性别者的父母提供指导与支持，帮助他们理解和接纳孩子的性别认同；同时也希望包含孩子如何处理与父母的关系的一些相关资料。
社群与个人故事:
  name: 社群与个人故事
  description: 该目录收录了跨性别个体的生命故事与个人经历，展示了他们在性别认同和过渡过程中的真实自述，以及面对社会传统观念的挑战。通过这些故事，力求增进对跨性别群体的理解与支持。
社群与个人故事/个人故事:
  name: 个人故事
  description: 本目录收录了跨性别个体的真实生命故事与过渡经历，旨在呈现他们的内心感受和生活经历，以期增进对跨性别群体的理解和支持。
