name: 父母
description: 本目录旨在为跨性别者的父母提供指导与支持，帮助他们理解和接纳孩子的性别认同；同时也希望包含孩子如何处理与父母的关系的一些相关资料。
curator: ''
source: ''
tags:
- 父母
- 跨性别
- 教育
- 支持
- 经验分享
license: ''
files:
- name: q-a-for-parents-family-of-transgender-2011-simplified-chinese
  filename: q-a-for-parents-family-of-transgender-2011-simplified-chinese.pdf
  description: 本文件是专为跨性别和性别多样青少年的父母及家庭成员提供的问答小册子，旨在指导他们如何支持、理解和接纳跨性别孩子的真实自我。文件中强调了重要的家长责任，以及如何为孩子创造一个安全和健康的成长环境。文中包含词汇表，帮助家长理解与跨性别相关的术语。
  type: document
  format: PDF Document
  size: 2292264
  md5: e9be2c03c19045694b75d77cf720decc
  date: '2011'
  archived: '2024-10-27 19:06:41'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 青少年
  - 亲子关系
  - 支持
  - 教育资源
  - 问答小册子
  page: q-a-for-parents-family-of-transgender-2011-simplified-chinese_page.md
subdirs: []
