name: 社群与个人故事
description: 该目录收录了跨性别个体的生命故事与个人经历，展示了他们在性别认同和过渡过程中的真实自述，以及面对社会传统观念的挑战。这里更倾向于社群自媒体的发帖，如果是新闻报道，请放在新闻目录下。
curator: ''
source: ''
tags:
- 跨性别
- 生命故事
- 个人经历
- 真实自述
- 性别认同
license: ''
files: []
subdirs:
- 个人故事
- 书籍
