name: 书籍
description: 这一目录包含了关于跨性别群体的书籍，涉及个人的生命故事与过渡经历，以真实的生动故事反映跨性别者的生存现状，帮助人们更好地理解和认同这些经历。
curator: ''
source: ''
tags:
- 生命故事
- 过渡经历
- 跨性别文学
- 真实记录
- 个人经历
license: ''
files:
- name: KS_故事-_克氏综合征
  filename: KS_故事-_克氏综合征.pdf
  description: 《KS 故事》是一本深入探讨克氏综合征（Klinefelter’s Syndrome, KS）的资料指南，旨在为患者、家人及专业人士提供全面的信息。本书的编纂者Iain
    W McKinlay本身是KS患者，他以51个访谈及多年的研究成果为基础，汇集了全球医学专家和支持组织的信息。这本书从症状、历史、医学、心理、社会影响等多个维度详细解读了KS，力求让读者对这一罕见遗传病有更全面的了解。此外，它还探讨了患者的情感与心理状态，并鼓励患者与他人分享自身经历，助于减轻孤独感。本书特别适合那些希望进一步了解自己的情况，或希望得到情感上的支持与理解的家庭和朋友们。
  type: document
  format: PDF Document
  size: 1145392
  md5: 18b1dc0f000f562fccaf410f67e83e22
  date: 2013年4月16日
  archived: '2024-10-30 06:03:56'
  link: http://ym.ymcs.top:1258/UploadFiles/images/source/20170607114429%E5%85%8B%E6%B0%8F%E7%BB%BC%E5%90%88%E5%BE%81%E4%BF%A1%E6%81%AF%E6%8C%87%E5%8D%97%E5%92%8C%E6%B7%B1%E5%85%A5%E7%A0%94%E7%A9%B6.pdf
  creator: ''
  tags:
  - 克氏综合征
  - 生命故事
  - 医疗资源
  - 心理健康
  - 支持组织
  - 医学研究
  - 患者经历
  - 性别认同
  - 法律政策
  page: KS_故事-_克氏综合征_page.md
- name: 一个精神病医生的手记_-_钟健夫_-_1992
  filename: 一个精神病医生的手记_-_钟健夫_-_1992.pdf
  description: 《一个精神病医生的手记》是一本由精神病医生钟健夫撰写的著作，书中记录了医生在精神病院的日常观察与心理分析。全书共分为九章，深入探讨了有关精神疾病、性别认同以及社会对待精神病患者的态度。首先，书中描述了患者从心理咨询室涌向精神病院的背景，展示了医院中患者的多样性，包括性别认同和性行为的异常案例。特别是在第三章‘性行为怪诞的人’中，有提及‘自认为女人的男人’的案例，揭示了在跨性别者心理状态与社会期待之间的矛盾。此外，书中对精神病和文化因素的关系，以及精神病学领域的诸多问题进行了深刻的思考与批判，为读者了解当时社会对精神病患者的理解和对待提供了重要的参考。最后，书附录部分也包含对中国精神病预防和治疗的历史回顾。
  type: document
  format: PDF Document
  size: 3247048
  md5: e0990999df17b7b377eba468eb5acfa2
  date: 未知
  archived: '2024-10-28 22:09:18'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 精神病
  - 性别认同
  - 心理健康
  - 医疗记录
  - 社会态度
  - 文化因素
  - 中国精神病史
  page: 一个精神病医生的手记_-_钟健夫_-_1992_page.md
- name: 中国“变性人”现象_方刚_1996_广州出版社
  filename: 中国“变性人”现象_方刚_1996_广州出版社.pdf
  description: 该文件名为《中国“变性人”现象》，由方刚撰写，发表于1996年，广州出版社出版。该书深入探讨了中国的变性人群体，记录了他们的生活故事、社会现状以及面临的挑战和困境。书中包含大量第一手资料，反映了变性人在生活和心理认同上的过渡过程，以及他们对社会接纳度的期待与追求。此文献不仅是对个体经历的描述，也是对当时中国社会对于跨性别群体认知的反思与批判，具有重要的学术与人文价值。
  type: document
  format: PDF Document
  size: 12613192
  md5: b816af5959f12bb4e786ef2cbc9b0da8
  date: '1996'
  archived: '2024-10-28 22:09:00'
  link: ''
  creator: ''
  tags:
  - 变性人
  - 生命故事
  - 医疗资源
  - 社会现状
  - 法律政策
  - 个人经历
  - 中国跨性别
  - 方刚
  page: 中国“变性人”现象_方刚_1996_广州出版社_page.md
- name: 女人梦——中国变性第一人
  filename: 女人梦——中国变性第一人.pdf
  description: 《女人梦——中国变性第一人》是一本关于中国首位变性女性的传记，记录了她的生命故事与过渡经历。在书中，作者详细讲述了自己从男性身份转变为女性的心理历程与身体变化，包括面对社会歧视的挑战以及内心的挣扎。同时，书中也分享了她在变性过程中的医疗经历，提供了对跨性别者在中国社会中所面临的法律和医疗资源的深刻见解。此外，这本书还探讨了社会对跨性别者的态度以及如何寻求和争取自身的权利与尊重，是了解中国跨性别群体的重要文献之一。
  type: document
  format: PDF Document
  size: 63952472
  md5: 420882df1ea11f08490be296c1467d2c
  date: 未知
  archived: '2024-10-28 22:09:01'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 变性
  - 个人故事
  - 社会环境
  - 医疗资源
  - 法律政策
  page: 女人梦——中国变性第一人_page.md
- name: 我的一生_刘培麟日记_-_刘培麟_唐冠华_-_2019
  filename: 我的一生_刘培麟日记_-_刘培麟_唐冠华_-_2019.pdf
  description: 这是刘培麟的个人日记合集，记录了他长达数十年的生活经历和内心感受。刘培麟于1956年2月出生，自幼抱养，生活在青岛。在日记中，他提到坚持写日记的经历，并表达了对生活中艰难时刻的思考和坚定信念。他分享了自己从任性穿着女装到经历社会抉择的心路历程，以及他在生活波折中对自我身份的认同。书中也提及了与志愿者和朋友们共同努力出版这本书的感人故事，体现了社会支持与人道关怀的重要性。
  type: document
  format: PDF Document
  size: 12471353
  md5: 76c60b0a18a36865f4ff6ae4592b3210
  date: '2019-09-01'
  archived: '2024-10-28 22:09:18'
  link: ''
  creator: ''
  tags:
  - 人生故事
  - 医疗经历
  - 跨性别
  - 法律与政策
  - 社会环境
  - 个人成长
  - 志愿者支持
  - 自我认同
  page: 我的一生_刘培麟日记_-_刘培麟_唐冠华_-_2019_page.md
- name: 纠正上帝的错误_“中国变性手术之父”何清濂的非常记忆_吴兴人_2005_上海文艺出版社
  filename: 纠正上帝的错误_“中国变性手术之父”何清濂的非常记忆_吴兴人_2005_上海文艺出版社.pdf
  description: 本书名为《纠正上帝的错误：‘中国变性手术之父’何清濂的非常记忆》，由吴兴人撰写，出版于2005年，由上海文艺出版社发行。这本书详细记录了何清濂的个人经历与他在中国变性手术领域的重要贡献。书中不仅探讨了变性手术的技术与医学进步，还反映了何清濂在推进跨性别权利与医疗资源方面的斗争与努力。通过个人故事与医学角度的结合，读者可以了解到跨性别者在手术和社会适应过程中面临的挑战，以及如何通过自身经历推动社会对跨性别问题的认知与接纳。
  type: document
  format: PDF Document
  size: 20567667
  md5: 9f2dff3fcef6c06febe0c8b1e68a91d6
  date: '2005'
  archived: '2024-10-28 22:09:01'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 变性手术
  - 何清濂
  - 生命故事
  - 医疗资源
  - 社会环境
  page: 纠正上帝的错误_“中国变性手术之父”何清濂的非常记忆_吴兴人_2005_上海文艺出版社_page.md
- name: 蝶变_一个变性丽人的心灵纪实_隋易_1998_内蒙古人民出版社
  filename: 蝶变_一个变性丽人的心灵纪实_隋易_1998_内蒙古人民出版社.pdf
  description: 《蝶变：一个变性丽人的心灵纪实》是一本关于变性女性隋易的个人经历和心路历程的书籍。她在书中详细叙述了自己作为变性人的生活故事，包括她的性别认同、过渡过程以及在社会中的遭遇和挑战。书中描绘了她如何面对家庭、社会以及自我的挣扎，体现了跨性别人士在追寻自我认同过程中的艰辛与勇气。此外，隋易还分享了她对于跨性别者在医疗、法律及社会环境等方面的看法与建议，以期提高人们对跨性别群体的理解与包容。
  type: document
  format: PDF Document
  size: 20150817
  md5: a0b951e49282cb65a28099ead6ce1fe1
  date: '1998'
  archived: '2024-10-28 22:09:01'
  link: ''
  creator: ''
  tags:
  - 变性经历
  - 性别认同
  - 自我成长
  - 法律与社会
  - 医疗资源
  - 跨性别故事
  page: 蝶变_一个变性丽人的心灵纪实_隋易_1998_内蒙古人民出版社_page.md
- name: 谁来决定你的性别_——中国首部跨性人电影_《香平丽》_王梆
  filename: 谁来决定你的性别_——中国首部跨性人电影_《香平丽》_王梆.pdf
  description: 《谁来决定你的性别——中国首部跨性人电影《香平丽》》是一本聚焦于跨性人群体生活与身份的书籍，探讨了跨性别者在社会、法律和医疗等方面所面临的挑战和问题。这本书从电影的角度出发，讲述了影片《香平丽》的创作背景、拍摄过程以及其对社会理解跨性别问题的影响和意义。书中包含了导演和演员的访谈，分享了他们对跨性别话题的看法，以及电影如何通过故事化的形式促使观众对跨性别者的理解与同情。
  type: document
  format: PDF Document
  size: 381878
  md5: ac2861b8a3bea08a66a0a7e046ef66ef
  date: 未知
  archived: '2024-10-30 15:43:52'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 电影
  - 社会问题
  - 性别认同
  - 生命故事
  - 文化表达
  page: 谁来决定你的性别_——中国首部跨性人电影_《香平丽》_王梆_page.md
- name: 跨性别ABC
  filename: 跨性别ABC.pdf
  description: 《跨性别ABC》是一本关于跨性别相关知识的书籍，编译于2012年。书中详尽解释了跨性别的多个相关概念，如性别认同、性别表达及跨性别者的不同身份，并且探讨了性别焦虑、人们如何确认自己的跨性别身份及性别过渡的过程。书中不仅回答了许多常见问题，例如跨性别认同是否为精神疾病，跨性别与性倾向之间的关系等，还提供了生动的真实经历分享和专家见解。此外，书中列举了各类跨性别的相关术语及定义，强调了对跨性别者的理解和支持的重要性。
  type: document
  format: PDF Document
  size: 246245
  md5: c9e07979861e9184cde04f07f5c9bd6d
  date: 2012年7月
  archived: '2024-10-30 06:39:06'
  link: https://docs.transonline.org.cn/files/Transgender_ABC.pdf
  creator: ''
  tags:
  - 跨性别
  - 性别认同
  - 性别表达
  - 变性手术
  - 激素替代治疗
  - 法律与政策
  - 医疗资源
  - 生存现状
  - 社会支持
  - 心理健康
  page: 跨性别ABC_page.md
subdirs: []
