name: RLE
description: 本目录包含跨性别者的变装指导与经验分享，旨在帮助有志于探索自己性别认同的人士，从基础到进阶掌握女装技巧，提供实用的变装手册和声音训练资源。
curator: ''
source: ''
tags:
- 跨性别
- 变装
- 女装
- 性别认同
- 经验分享
license: ''
files:
- name: 女装入门到精通(1)
  filename: 女装入门到精通(1).pdf
  description: 本文件为一本关于女装文化的入门指南，讨论了女装的必要性、体魄的差异以及化妆和穿着女性服装的技巧。作者分享了个人的见解和经历，旨在帮助对女装有兴趣的人士更好地理解和体验这一文化。文中还提到了在COSPLAY活动中女装的流行，以及女装者在成长过程中的各种挑战与乐趣。
  type: document
  format: PDF Document
  size: 1469096
  md5: c00f239331c6379cacc76e9c40c6b35f
  date: '2024-10-27'
  archived: '2024-10-27 19:05:46'
  link: ''
  creator: ''
  tags:
  - 女装
  - COSPLAY
  - 性别认同
  - 跨性别文化
  - 生活指导
  page: 女装入门到精通(1)_page.md
- name: 好想做个女孩子-伪娘养成手册
  filename: 好想做个女孩子-伪娘养成手册.pdf
  description: 此文件为《好想做个女孩子——伪娘养成手册》，主要探讨了女装文化及其欣赏者的过渡体验。文件中包含女装所需的身体与心理准备，包括处理体质差异、减肥、选择女性服装的技巧等内容，旨在帮助对女装感兴趣的人士更好地理解和体验女装文化。
  type: document
  format: PDF Document
  size: 1469096
  md5: c00f239331c6379cacc76e9c40c6b35f
  date: '2024-10-27'
  archived: '2024-10-27 19:03:21'
  link: ''
  creator: ''
  tags:
  - 女装文化
  - 跨性别
  - 伪娘
  - 生活指南
  - 过渡经历
  - COSPLAY
  - 性别认同
  page: 好想做个女孩子-伪娘养成手册_page.md
- name: 好想做个女孩子【伪娘养成手册】[正式版]
  filename: 好想做个女孩子【伪娘养成手册】[正式版].rar
  description: 该文件为《好想做个女孩子【伪娘养成手册】》的正式版，内容涉及伪娘文化的相关指南与经验分享，主要针对希望进行性别表达转变的个体，提供实践建议与心理支持，探索跨性别身份的认同与表达。
  type: other
  format: Unknown Format
  size: 41750
  md5: 1adf4d84605b2324562b848cd7303c27
  date: '2024-10-27'
  archived: '2024-10-27 19:03:21'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 伪娘
  - 性别认同
  - 生活指南
  - 经验分享
  page: 好想做个女孩子【伪娘养成手册】[正式版]_page.md
- name: 完全变装手册最后5章附英语原文
  filename: 完全变装手册最后5章附英语原文.pdf
  description: 该文件是《完全变装手册》的最后五章及其英文原文的翻译，内容主要涉及变装者的穿着、化妆和生活建议。翻译者分享了跨性别者在应对自我认同和公共形象时所需遵循的多项作业，包括外观的改造和女性化身份的体验。该手册旨在为变装者提供指导和支持，帮助他们更好地融入女性角色。
  type: document
  format: PDF Document
  size: 612359
  md5: a9628752ee15481d1729762af49ed2fd
  date: '2024-10-27'
  archived: '2024-10-27 19:03:21'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 变装
  - 性别认同
  - 穿着建议
  - 化妆指南
  - 生活经历
  page: 完全变装手册最后5章附英语原文_page.md
subdirs:
- 变成女孩子声音
