name: 健康护理
description: 此目录收录了与跨性别者健康护理相关的资源与信息，包括心理支持、手术经验及激素治疗等方面的内容。这些资料旨在帮助跨性别者了解和获取所需的医疗资源，支持他们的过渡过程。
curator: ''
source: ''
tags:
- 医疗资源
- 心理支持
- 手术
- 激素治疗
- 跨性别健康
license: ''
files: []
subdirs:
- 其他
- 心理
- 手术
- 激素
