name: 法律
description: 该目录包含与跨性别者相关的法律权益和政府法规的信息，旨在提供跨性别社区在法律政策方面的参考与指引，包括公证服务与法律法规的解读。
curator: ''
source: ''
tags:
- 跨性别法律
- 法律政策
- 社会环境
- 公证
- 政府法规
license: ''
files: []
subdirs:
- 保险
- 公证
- 其他
- 法律法规与政府文件
- 法律评论与文献
