name: 文学与艺术作品
description: 此目录收录与跨性别相关的文学及艺术作品，包括小说、诗歌、绘画等，通过艺术表达跨性别者的生活体验和内心世界，展示他们的故事与情感。
curator: ''
source: ''
tags:
- 跨性别
- 文学
- 艺术
- 生命故事
- 文化表达
license: ''
files:
- name: 王安黛-中篇严肃悬疑-缺耳女_二稿修正版
  filename: 王安黛-中篇严肃悬疑-缺耳女_二稿修正版.docx
  description: 本文件为王安黛撰写的中篇小说《缺耳女》的二稿修正版，涵盖了跨性别主题及个人身份的探索。故事从一位失忆的女人的视角展开，她在从医院苏醒后只记得部分片段，却无法理解自己身体的变化和周遭人隐藏的秘密。小说以多位不同叙述者的视角交替叙述，时间线横跨多个年份，揭示了主要角色在寻求身份认同过程中的矛盾与挣扎。作品不仅探讨了跨性别者的生存状态，还涉及到感情、记忆以及社会对跨性别身份的偏见与误解。文中精致的描写力求真实地再现了角色心理的复杂性。
  type: document
  format: Microsoft Word Document (OpenXML)
  size: 220567
  md5: 26de3327da3eb924a70d89054d69d11a
  date: 未知
  archived: '2024-10-30 15:47:08'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 身份认同
  - 失忆
  - 个人故事
  - 社会偏见
  - 王安黛
  - 文学作品
  page: 王安黛-中篇严肃悬疑-缺耳女_二稿修正版_page.md
- name: 药娘的天空
  filename: 药娘的天空.pdf
  description: 《药娘的天空》是一部关于跨性别女孩苏雨晴生活和成长的小说。从她的视角，读者看到一个面临家庭欺压与自身认同的年轻人在成长过程中经历的挣扎与挑战。故事中，苏雨晴与父母之间的关系紧张，因其性别认同遭遇家庭暴力与社会的偏见，最终选择离家出走，寻找属于自己的生活。在小城市的冒险中，她努力尝试寻找工作与住所，凭借微薄的收入努力维持生计。小说通过描绘苏雨晴的内心独白与她身边的环境，展现了一个跨性别者在社会中的艰难生存现状和不懈奋斗的精神。文字中对于她的感情、对药物的依赖、与家人之间的隔阂，以及对于未来的渴望，统统呈现了出来。
  type: document
  format: PDF Document
  size: 22571390
  md5: 068ef1ef592f2ae5ef1561778550e40f
  date: 未知
  archived: '2024-10-30 07:32:46'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 生存故事
  - 成长小说
  - 家庭关系
  - 社会偏见
  - 性别认同
  - 青春成长
  - 心理挣扎
  page: 药娘的天空_page.md
subdirs: []
