name: 个人故事
description: 本目录收录了跨性别个体的真实生命故事与生活经历，旨在呈现他们的内心感受。如果是新闻报道，请放在新闻目录而不是这里。
curator: ''
source: ''
tags:
- 跨性别
- 个人故事
- 生命经历
- 过渡经历
- 真实记录
license: ''
files:
- name: 2017秋季泰国法政大学交流心得
  filename: 2017秋季泰国法政大学交流心得.pdf
  description: 该文件为2017年秋季关于在泰国法政大学进行交换学习的心得体会。作者分享了自己在泰国的交换生活和学习经历，包括对泰国法政大学的介绍及其丰富的学术课程。作者详细描述了他们在曼谷的生活，包括穿校服的学风、通勤经历、以及在葬礼期间民众的悲伤气氛。特别提到的东南亚性别研究课程中，探讨了东南亚社会的性别议题和变性人文化，反映了当前社会对性别少数派的认知与挑战。此外，作者还分享了学习泰语的过程和在泰国各地旅行的感受，展现了对泰国文化的喜爱与思考。
  type: document
  format: PDF Document
  size: 123399
  md5: 4cdb65d30c36ecc8d3a3a9b7624fa6ae
  date: '2017-08-01'
  archived: '2024-10-30 06:37:07'
  link: https://fao.fudan.edu.cn/_upload/article/files/1f/81/bf0e55664a93ade75f6b49df15ed/7d3c3b8f-ad63-476f-a5d9-8477e6aa9abf.pdf
  creator: ''
  tags:
  - 泰国法政大学
  - 交换留学
  - 性别研究
  - 东南亚文化
  - 个人成长
  - 留学经历
  - 变性人文化
  page: 2017秋季泰国法政大学交流心得_page.md
- name: “灵魂”对“肉体”的背叛——变性人现象综述_祁冬涛
  filename: “灵魂”对“肉体”的背叛——变性人现象综述_祁冬涛.pdf
  description: 本文件为祁冬涛撰写的关于变性人现象的综述。文章探讨了变性人在历史中的存在与社会的认知，特别是在中国历史上变性人所面临的社会环境和医疗挑战。资料中引用了多位历史人物的案例，分析了性别认同的复杂性及变性人经历的内心挣扎。文中提到：变性人常常遭受灵魂与肉体之间的分裂痛苦，并对医学手术的渴望，以及随之而来的社会压力。文章还讨论了变性人的生活状况、法律政策、社会对变性现象的态度，以及对现代科学对变性人的理解与宽容的期望。
  type: document
  format: PDF Document
  size: 309104
  md5: b73d65fab7187372ac1e789f5a0ef37d
  date: 未知
  archived: '2024-10-30 15:44:24'
  link: ''
  creator: ''
  tags:
  - 变性人
  - 性别认同
  - 社会态度
  - 历史文献
  - 心理学
  - 医疗资源
  - 法律政策
  page: “灵魂”对“肉体”的背叛——变性人现象综述_祁冬涛_page.md
- name: 中国首位变性人状告医院始末_李玉林
  filename: 中国首位变性人状告医院始末_李玉林.pdf
  description: 本文件记录了中国首位变性人李玉林因变性手术遇到的一系列法律争议与个人经历的详细叙述。李玉林分享了自己从男孩到女性身份的过渡过程，描述了手术前的期待与手术后的痛苦，以及在此过程中在家庭、社会与法律层面遭遇的种种挑战。在与医院的官司中，她揭露了医院在手术和护理过程中的过错，未能达到其所期望的变性效果，致使其生活质量大大下降。文件中提到，李玉林曾向杭州市整形医院提起诉讼，争取合法权益，并希望借此案件为后续变性人群体维护自身权利提供借鉴与参考。
  type: document
  format: PDF Document
  size: 728924
  md5: 32dc3f16aebe8788fbade96cc7294f31
  date: 未知
  archived: '2024-10-30 15:45:19'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 生命故事
  - 医疗经历
  - 法律诉讼
  - 性别平等
  - 社会环境
  - 变性手术
  - 李玉林
  page: 中国首位变性人状告医院始末_李玉林_page.md
- name: 今后的路并不平坦——记“变性人”邹丹妮_王莉
  filename: 今后的路并不平坦——记“变性人”邹丹妮_王莉.pdf
  description: 本文件记录了跨性别者邹丹妮的生命故事与过渡经历。邹丹妮分享了她在变性过程中的心理挑战和社会适应，她强调了社会对跨性别者的误解和偏见，讲述了自己在家庭、学校及社会环境中的经历与挣扎。同时，她也提到了一些关键的支持资源和帮助，使她能更好地理解自己的身份并进行自我接纳。通过邹丹妮的故事，我们能够更加深入地理解跨性别者的生活现状与心理状态，促进社会对这一群体的理解与支持。
  type: document
  format: PDF Document
  size: 644943
  md5: 6e614b08e2bdd54af5c046256b8c7161
  date: 未知
  archived: '2024-10-30 15:44:46'
  link: ''
  creator: ''
  tags:
  - 生命故事
  - 跨性别经历
  - 社会适应
  - 心理挑战
  - 支持资源
  page: 今后的路并不平坦——记“变性人”邹丹妮_王莉_page.md
- name: 从一个变性人的痛苦说起……_储兆瑞
  filename: 从一个变性人的痛苦说起……_储兆瑞.pdf
  description: 本文件记录了储兆瑞作为一名跨性别者在经历性别认同转变中的痛苦与挑战。通过个人叙述，分享了他在转型过程中遇到的种种困难，包括身体的变迁、内心的挣扎，以及社会与亲友的反应。故事深刻描绘了在社会压力和个人真实情感之间的挣扎，展现了一个变性人寻求自我认同与接受的真实历程。文中可能提及到的关键句子包括一些描述个人情感的内心独白和对外界反应的思考。这是一个真实而又感人的故事，旨在引发对跨性别者经历的理解与思考。
  type: document
  format: PDF Document
  size: 1359629
  md5: 99e725a1da9a00f10a3c826e95c0259c
  date: 未知
  archived: '2024-10-30 15:43:25'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 个人故事
  - 痛苦经历
  - 性别认同
  - 社会反应
  - 情感表达
  page: 从一个变性人的痛苦说起……_储兆瑞_page.md
- name: 从变装到变性_-_他（她）的真实自述
  filename: 从变装到变性_-_他（她）的真实自述.txt
  description: 这篇自述记录了一个跨性别者的生命历程，从变装到变性后的真实经历，分享了个人在变性前后的心理感受、社会接纳、日常生活的挑战以及对变性手术的深刻反思。作者详细讲述了变性给她带来的各种困扰，例如社会认同、情感关系、工作环境等，提醒读者思考变性决策的复杂性与个人心理的准备。同时，也有其他相关人士的留言支持与讨论，展示了跨性别社群中的互动和关怀。
  type: document
  format: Plain Text
  size: 29100
  md5: a3b5784e055742edc39f694fff16a9e3
  date: 未知
  archived: '2024-10-28 05:12:47'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 变性经历
  - 个人故事
  - 生命故事
  - 社会接纳
  - 心理健康
  - 生活挑战
  - 性别认同
  - 性别政治
  page: 从变装到变性_-_他（她）的真实自述_page.md
- name: 变性人生活辛酸
  filename: 变性人生活辛酸.pdf
  description: 该文件是一篇跨性别者的生活故事，讲述了主人公在澳大利亚的经历和辛酸的过渡过程。内容涉及到个人的变性经历、法律问题以及社会环境的挑战。文本中提及主人公在进行变性手术后，经历了重重困难，包括与房东的矛盾以及在寻求社会接纳中的挣扎。文中描绘了一位名为米华的变性人，她与宠物猫萨里的“婚礼”成为了她逆境中的一丝慰藉。文件深刻反映了变性人在社会中面临的真实挑战和歧视，尤其是失业和社会支持不足的现状。
  type: document
  format: PDF Document
  size: 143480
  md5: 608cf0e40e3ccff01a4f56b18d73c8fe
  date: 未知
  archived: '2024-10-30 15:45:24'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 个人故事
  - 变性经历
  - 社会歧视
  - 法律问题
  - 医疗资源
  - 生活现状
  page: 变性人生活辛酸_page.md
- name: 姜昆与我巧遇变性人_吴钢
  filename: 姜昆与我巧遇变性人_吴钢.pdf
  description: 该文档记录了姜昆与吴钢在新加坡相遇的经历，描绘了吴钢作为变性人的生活境遇及其社会背景。通过姜昆的视角，展现了新加坡华人社会的复杂性，以及变性人在该社会中的生存状态。文中提及了‘人妖’这一现象，以及新加坡政府推行华语运动对文化交流的影响。局部描述中提到在与小蓝的交谈中，讨论了新加坡在面对不同文化与社会变迁时的挑战，并透露出‘人妖’的真实身份及其在社会中遭受的偏见和理解。文章还探讨了跨性别者的社交生活与经济活动，尤其是在红灯区环境中的生存状况，反映了新加坡独特文化交流与融合的一个侧面，诸如：“新加坡路边的快速冲印店很多，一会儿照片就出来了”，“我为海外华人能在异国他乡创造出一个如此美丽富饶的国家感到由衷的喜悦。”
  type: document
  format: PDF Document
  size: 310036
  md5: 29e01be09fa6aa77479ef1611ad741aa
  date: 未知
  archived: '2024-10-30 15:47:07'
  link: ''
  creator: ''
  tags:
  - 跨性别故事
  - 新加坡
  - 社会现状
  - 文化交流
  - 变性人
  - 人妖现象
  - 华人社区
  page: 姜昆与我巧遇变性人_吴钢_page.md
- name: 我在泰国做“人妖”_尼莎
  filename: 我在泰国做“人妖”_尼莎.pdf
  description: 这份文件包含了一个名叫尼莎的跨性别者在泰国作为“人妖”的生活故事，描绘了她在艰难环境中的过渡经历。文中详细介绍了她的背景，包括随父亲来到秦国的经历，她如何开始接受女性化训练和注射激素，以及她为了生存而选择成为人妖的原因。尼莎提到，由于经济拮据，她在求生的无奈中走上了这一条路，并面临着许多挑战与困境。文件中还透露了她在演出团体中的角色以及与其他“人妖”的生活。同时，也反映了她渴望过上普通生活的梦想，以及跨性别者在社会中面临的偏见与挑战。
  type: document
  format: PDF Document
  size: 235626
  md5: 839f7c0a62dbc921301e9b537b3b9def
  date: 未知
  archived: '2024-10-30 15:44:29'
  link: ''
  creator: ''
  tags:
  - 生命故事
  - 过渡经历
  - 跨性别
  - 人妖
  - 泰国
  - 社会挑战
  - 性别认同
  - 生存经验
  page: 我在泰国做“人妖”_尼莎_page.md
- name: 我的性别我做主_夏日艳阳
  filename: 我的性别我做主_夏日艳阳.pdf
  description: 该文件记录了刘晓晶的个人故事，讲述了她作为一个跨性别女性的成长经历与心理历程。她在哈尔滨出生，从小就认定自己是女性，并经历了强烈的性别认同冲突。通过与家人的沟通及医院的支持，她最终决定进行变性手术来实现自我认同。文件中详细描绘了她的手术过程，以及术后心理和身体的转变，强调了亲友的接纳对她的重要性。此外，文中提到刘晓晶在变性手术后的社会接受度，她参加了各种比赛并获得多个奖项，成为了公认的变性美女。整体上，该文档不仅反映了个人故事，还涉及社会环境对跨性别者生存状况的影响。
  type: document
  format: PDF Document
  size: 482621
  md5: 7796cd478efa73c186390aaf18a44540
  date: 未知
  archived: '2024-10-30 15:44:17'
  link: ''
  creator: ''
  tags:
  - 变性经历
  - 跨性别
  - 个人故事
  - 医疗经历
  - 社会接受
  - 心理转变
  - 女性身份
  - 中国变性人
  page: 我的性别我做主_夏日艳阳_page.md
- name: 我骄傲我奉献真色彩
  filename: 我骄傲我奉献真色彩.pdf
  description: 这份文件记录了麦肯锡公司对 LGBTQ 社群的支持，特别关注了跨性别和年轻人群体。文中提到，麦肯锡参与了多个城市的骄傲庆典，积极推动多元与包容的企业文化。讨论了麦肯锡如何参与
    Trevor 计划，这是一项为 LGBTQ 青少年提供心理支持的公益组织。文件还提到麦肯锡为 Trevor 计划提供咨询服务的历史，以及鲍达民总裁的获奖情况与其对
    LGBTQ 群体支持的重要性。该文件通过讲述具体案例和数据信息，反映了麦肯锡在支持性少数群体方面的贡献与努力，强调了多元化的重要性和对青少年的心理支持，尤其是在自杀风险方面的警示。
  type: document
  format: PDF Document
  size: 511412
  md5: 7c786689aac42bfe912165d5491556bd
  date: 未知
  archived: '2024-11-01 09:16:49'
  link: https://www.yunbaogao.cn/index/partFile/1/mckinsey/2021-12/1_33975.pdf
  creator: ''
  tags:
  - 跨性别
  - LGBTQ
  - 骄傲庆典
  - 心理支持
  - Trevor计划
  - 企业责任
  - 性少数群体
  - 多元文化
  - 社会认可
  page: 我骄傲我奉献真色彩_page.md
- name: 拯救可橙：被父母强送矫治的跨性别者
  filename: 拯救可橙：被父母强送矫治的跨性别者.pdf
  description: 本文件讲述了一位跨性别者的个人故事，重点展现其在被父母强送接受矫治过程中经历的痛苦和挣扎。作者详细描述了自己对身份认同的反思，以及在这一过程中所面临的社会压力和家庭不理解。文中提到的真实案例和情感表达，揭示了跨性别者在成长中的复杂经历。这份文件不仅展示了个体的生命历程，更是对跨性别者面临的挑战及其求生存权利的深刻反思。
  type: document
  format: PDF Document
  size: 2904100
  md5: cc18a34320ff30ec3b6bdaaf2b58ef62
  date: 未知
  archived: '2024-10-30 15:44:11'
  link: ''
  creator: ''
  tags:
  - 跨性别者
  - 个人故事
  - 家庭矫治
  - 身份认同
  - 社会压力
  - 生命故事
  page: 拯救可橙：被父母强送矫治的跨性别者_page.md
- name: 泰国“人妖”是这样“炼”成_子——一名广西男青年的自述_杜启荣
  filename: 泰国“人妖”是这样“炼”成_子——一名广西男青年的自述_杜启荣.pdf
  description: 本文件为一名来自广西的男青年杜启荣讲述的个人故事，标题为《泰国“人妖”是这样“炼”成_子》。该文档探讨了个人在性别认同和社会接受之间的经历，以及在泰国文化中对“人妖”这一身份的理解与认知。文本中描绘了他如何在社会与文化的交织中寻找自己的身份，并对转变过程中所面临的挑战和机遇进行了深入剖析。杜启荣分享了他在成长过程中对于性别的思考，并阐述了他对自身身份的认同，这是一个关于勇气、自我真实及接受的感人故事。
  type: document
  format: PDF Document
  size: 3392142
  md5: db01be0b858b55c31a645048835e6f1b
  date: 未知
  archived: '2024-10-30 15:43:58'
  link: ''
  creator: ''
  tags:
  - 个人故事
  - 性别认同
  - 跨性别经历
  - 社会接纳
  - 文化认知
  - 广西
  - 人妖
  page: 泰国“人妖”是这样“炼”成_子——一名广西男青年的自述_杜启荣_page.md
- name: 烦恼多多话变性_项力
  filename: 烦恼多多话变性_项力.pdf
  description: 该文件是一篇关于跨性别者内心挣扎与变性手术的个人故事及社会现象的探讨。文章中讲述了许多跨性别者的经历，比如项力自述自己从男性到女性的心理变化，以及社会对变性人群的偏见和误解。文中提到一些关于变性手术的医学观点、社会批判与法律案例，反映出对变性人生活状态的深刻关注。其中谈及个人故事，例如一名跨性别者因早年被错误性别引导而产生的困惑，和变性手术后的迎接与挑战。同时，本文件也探讨了变性对家庭、婚姻甚至社会关系的影响，如父母的反应、伴侣的接受程度，以及变性人在就业和生活中面临的种种困境。
  type: document
  format: PDF Document
  size: 884971
  md5: 5e9d3c9d91418594f09b2d4388c00782
  date: 未知
  archived: '2024-10-30 15:45:52'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 变性手术
  - 生命故事
  - 社会现状
  - 心理健康
  - 法律政策
  - 个人经历
  page: 烦恼多多话变性_项力_page.md
- name: 秦惠英，你在哪里？_方刚
  filename: 秦惠英，你在哪里？_方刚.pdf
  description: 本文件名为《秦惠英，你在哪里？》，记录了秦惠英这一中国第一个公开变性人的真实故事。文件详细叙述了秦惠英从秦惠荣过渡到女性的心路历程，涉及她的家庭背景、教育情况、过渡手术的经历以及心理斗争。文件中的文字流露出秦惠英在变性过程中的勇敢与无奈，描述了她在医院接受变性手术的经过，以及周围人对此的态度变化。特别是当她决定公开身份时，她所面临的社会压力与个人情感的挣扎。内容中提到，“如果永远没有人站出来，大众的认知就永远不会改变。”这是她挑战传统观念、影响大众认知的重要尝试。
  type: document
  format: PDF Document
  size: 454618
  md5: 6852615ed39f779f9ddb314ba9e00919
  date: 未知
  archived: '2024-10-30 15:45:11'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 秦惠英
  - 变性人
  - 人生故事
  - 心理斗争
  - 社会压力
  - 性别认同
  - 医疗经历
  - 公开身份
  page: 秦惠英，你在哪里？_方刚_page.md
- name: 谁是中国首例变性人_谷雨生
  filename: 谁是中国首例变性人_谷雨生.pdf
  description: 本文件记录了中国首例变性人谷雨生的个人故事，探讨了她的成长背景、性别认同以及转型过程中的挑战与经验。通过谷雨生的亲身经历，文件对跨性别者在中国社会中的位置、面临的法律与医疗障碍，以及在社会文化环境中的生存状态进行了深入的剖析与反思。内容直指跨性别话题在公众视野中的缺失，同时提供了个人声音以增强对这一群体的了解与支持。
  type: document
  format: PDF Document
  size: 1143144
  md5: 7fca112a0832ee2a0620995d0585cfc0
  date: 未知
  archived: '2024-10-30 15:46:53'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 个人故事
  - 变性人
  - 谷雨生
  - 成长经历
  - 性别认同
  - 社会挑战
  page: 谁是中国首例变性人_谷雨生_page.md
- name: 超_规模集成电路VLSI_的共同开发者林恩康威Lynn_Conway__于6_9
  filename: 超_规模集成电路VLSI_的共同开发者林恩康威Lynn_Conway__于6_9.pdf
  description: 该文件讲述了跨性别女性林恩·康威（Lynn Conway）的生平故事及其对超大规模集成电路（VLSI）技术的重要贡献。林恩·康威于2023年6月9日去世，享年86岁。她不仅是一位杰出的工程师，还是一位积极的跨性别权利活动家。文件中提到，康威参与开发VLSI技术，她在1960年代及1970年代初期的研究开创了集成电路设计的新时代，极大地影响了现代电子设备的发展。详细描述了她的教育背景、职业生涯以及因性别认同而经历的挑战，尤其是在IBM工作的经历。文本中强调，康威在公共领域中的表现及对IEEE行为准则的影响，使她成为跨性别社区的重要代表。此外，文件还涉及到康威为推动技术创新做出的努力，以及对工程教育的贡献。
  type: document
  format: PDF Document
  size: 3508058
  md5: 83741baf3e0db3c8329c563d722b502c
  date: 未知
  archived: '2024-10-30 06:18:33'
  link: https://reportify-1252068037.cos.ap-beijing.myqcloud.com/media/production/n_gjbd1gccsbz70ciy30e5oq_36d44b77579091d5d32c5434b5195229_20240622112609.pdf
  creator: ''
  tags:
  - 林恩·康威
  - 跨性别权利活动家
  - 超大规模集成电路
  - VLSI技术
  - 电子工程
  - 生平故事
  - 性别认同
  - IEEE行为准则
  page: 超_规模集成电路VLSI_的共同开发者林恩康威Lynn_Conway__于6_9_page.md
- name: 阴阳大裂变——变性人的故事_杨昆_健康生活_2002
  filename: 阴阳大裂变——变性人的故事_杨昆_健康生活_2002.pdf
  description: 本文件《阴阳大裂变——变性人的故事》记录了跨性别者杨昆的个人经历与过渡故事。通过生动的叙述，杨昆分享了他在身份认同与社会适应过程中的挑战与精彩瞬间。他深入探讨了性别认同的复杂性，以及在家庭、朋友和社会支持系统中的经历。这篇文章不仅仅是个人的叙述，亦反映了广泛的社会问题和跨性别者的生存现状。
  type: document
  format: PDF Document
  size: 508880
  md5: 0729a800a9eae6fff87d0189e3c0b907
  date: '2002'
  archived: '2024-10-30 15:45:40'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 个人故事
  - 生命经历
  - 性别认同
  - 社会适应
  - 杨昆
  page: 阴阳大裂变——变性人的故事_杨昆_健康生活_2002_page.md
subdirs:
- 一个阉人的真实故事
