name: 个人故事
description: 本目录收录了跨性别个体的真实生命故事与过渡经历，旨在呈现他们的内心感受和生活经历，以期增进对跨性别群体的理解和支持。
curator: ''
source: ''
tags:
- 跨性别
- 个人故事
- 生命经历
- 过渡经历
- 真实记录
license: ''
files:
- name: 从变装到变性_-_他（她）的真实自述
  filename: 从变装到变性_-_他（她）的真实自述.txt
  description: 这篇自述记录了一个跨性别者的生命历程，从变装到变性后的真实经历，分享了个人在变性前后的心理感受、社会接纳、日常生活的挑战以及对变性手术的深刻反思。作者详细讲述了变性给她带来的各种困扰，例如社会认同、情感关系、工作环境等，提醒读者思考变性决策的复杂性与个人心理的准备。同时，也有其他相关人士的留言支持与讨论，展示了跨性别社群中的互动和关怀。
  type: document
  format: Plain Text
  size: 29100
  md5: a3b5784e055742edc39f694fff16a9e3
  date: 未知
  archived: '2024-10-28 05:12:47'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 变性经历
  - 个人故事
  - 生命故事
  - 社会接纳
  - 心理健康
  - 生活挑战
  - 性别认同
  - 性别政治
  page: 从变装到变性_-_他（她）的真实自述_page.md
subdirs:
- 一个阉人的真实故事
