name: 手术
description: 本目录包含与跨性别医疗护理和手术相关的资料，涵盖变性手术的流程、临床研究、手术护理及心理护理等内容。通过这些信息，旨在为跨性别者提供必要的手术知识和医疗资源，助力他们的身体过渡与心理适应。
curator: ''
source: ''
tags:
- 跨性别
- 变性手术
- 医疗资源
- 心理护理
- 术中护理
- 人生经历
- 手术流程
license: ''
files:
- name: MTF_流程
  filename: MTF_流程.pdf
  description: 此文档是关于在泰国Yanhee医院进行男变女（MTF）的变性手术指南与流程。文件详细阐述了进行手术的前提条件、流程、术前和术后注意事项、费用说明及可选择的额外手术项目。手术前的准备包括对患者心理状况的评估及各种证明文件的准备。
  type: document
  format: PDF Document
  size: 340955
  md5: c437b0c98fc4847073c1008331d75278
  date: 未知
  archived: '2024-10-28 00:01:33'
  link: ''
  creator: ''
  tags:
  - 变性手术
  - 跨性别
  - MTF
  - 医学指南
  - 性别确认
  - Yanhee医院
  - 泰国
  - 手术流程
  - 心理评估
  page: MTF_流程_page.md
- name: 一个变性手术专家的手记
  filename: 一个变性手术专家的手记.pdf
  description: 本文件是一份关于变性手术专家何清雳的记录，详细描述了他在医疗工作中接触的易性癖患者的经历，以及他所进行的变性手术案例。文章中提到易性癖在医学上的定义、患者的心理挣扎、社会的误解，以及通过手术改变生活的具体事例。何清雳通过他的文字，期望能增进社会对易性癖患者的理解、同情与支持。
  type: document
  format: PDF Document
  size: 1534779
  md5: 8b3f3bf112a5c23df62bc36a0103d48f
  date: 不详
  archived: '2024-10-27 06:25:36'
  link: ''
  creator: ''
  tags:
  - 变性手术
  - 易性癖
  - 医疗记录
  - 跨性别
  - 社会理解
  page: 一个变性手术专家的手记_page.md
- name: 变性手术的术中配合与护理
  filename: 变性手术的术中配合与护理.pdf
  description: 本文件详细描述了变性手术中的护理配合要点，特别是术中护理和器械护士的准备与配合要点。通过回顾性分析深圳北大医院8例变性手术案例，总结了如何提升手术配合质量，确保手术的顺利进行和患者的安全。本研究涵盖心理护理、术前准备、术中监测及器械管理等方面，强调了术中护理细节对手术成功的重要性。
  type: document
  format: PDF Document
  size: 236973
  md5: 78fc3772ee8c0081bbd753bedbc9a564
  date: 2006-08
  archived: '2024-10-27 06:25:36'
  link: ''
  creator: ''
  tags:
  - 变性手术
  - 术中护理
  - 医疗护理
  - 心理护理
  - 手术配合
  - 器械管理
  page: 变性手术的术中配合与护理_page.md
- name: 变性手术资料(1)
  filename: 变性手术资料(1).doc
  description: 该文件涉及跨性别者相关的变性手术资料。由于无法提取文档内容，具体信息未知。该文档归档于健康护理类别，可能包含有用的医疗信息和经验分享。
  type: document
  format: Microsoft Word Document
  size: 37888
  md5: d2d09d69df973015a230757902ac5e27
  date: 未知
  archived: '2024-10-27 06:27:01'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 健康护理
  - 变性手术
  - 医学资料
  - 经验分享
  page: 变性手术资料(1)_page.md
- name: 变性术典型病例_-_美容与再造整形手术实例彩色图谱·躯干、会阴及四肢分册_-_中国工具书网络出版总库_20170326044255
  filename: 变性术典型病例_-_美容与再造整形手术实例彩色图谱·躯干、会阴及四肢分册_-_中国工具书网络出版总库_20170326044255.png
  description: 本文件是关于变性手术的典型病例，包含躯干、会阴及四肢整形手术的实例图谱。这些彩色图谱详细展示了不同阶段的手术过程，提供了视觉参考以帮助理解手术步骤和效果。
  type: image
  format: PNG Image
  size: 12251346
  md5: 0f3cb10f542c32f73cbe00f81237bd9f
  date: 未知
  archived: '2024-10-28 00:01:33'
  link: ''
  creator: ''
  tags:
  - 变性手术
  - 整形外科
  - 医学图谱
  - 跨性别健康
  - 手术实例
- name: 性别重置术中阴蒂再造的临床研究_张连杰
  filename: 性别重置术中阴蒂再造的临床研究_张连杰.pdf
  description: 本文件是关于性别重置术中阴蒂再造的新方法的临床研究，旨在探讨使用阴茎背神经血管束结合部分包皮的复合组织瓣来实现更加真实和功能良好的阴蒂再造。这种方法应用于68例男性向女性的性别重置手术中，术后阴蒂成活率高，外观逼真且感觉敏锐。
  type: document
  format: PDF Document
  size: 1620936
  md5: 5485053c798795ca2eed849e5cb09537
  date: 2018-11
  archived: '2024-10-27 06:25:36'
  link: ''
  creator: ''
  tags:
  - 医学
  - 性别重置术
  - 阴蒂再造
  - 跨性别
  - 临床研究
  page: 性别重置术中阴蒂再造的临床研究_张连杰_page.md
- name: 易性癖外科治疗三例_李宏生
  filename: 易性癖外科治疗三例_李宏生.pdf
  description: 这份文件名为《易性癖外科治疗三例》，由于技术问题无法提取详细的文本内容。根据文件名称，推测该文件可能记录了三例关于易性癖（性别认同障碍）外科治疗的案例研究或医学心得。
  type: document
  format: PDF Document
  size: 79792
  md5: cc93e5856fc47fb7432d1e2c4e18c424
  date: 未知
  archived: '2024-10-27 06:24:55'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 医疗
  - 外科治疗
  - 易性癖
  - 案例研究
  page: 易性癖外科治疗三例_李宏生_page.md
- name: 易性癖外科治疗八例_杨东
  filename: 易性癖外科治疗八例_杨东.pdf
  description: 此PDF文件记录了一篇关于易性癖的外科治疗案例研究，分析了八例不同患者的手术过程、术后效果和治疗经验。这些案例为医疗专业人士提供了关于跨性别外科手术的具体见解和实践经验，有助于提升相关的临床治疗水平。
  type: document
  format: PDF Document
  size: 99555
  md5: 6313d521e561b440f713fdbb74030e84
  date: 未知
  archived: '2024-10-27 06:24:55'
  link: ''
  creator: ''
  tags:
  - 易性癖
  - 跨性别
  - 外科治疗
  - 医疗经验
  - 案例研究
  page: 易性癖外科治疗八例_杨东_page.md
- name: 易性癖的外科治疗进展_章建林
  filename: 易性癖的外科治疗进展_章建林.pdf
  description: 该文件涉及易性癖的外科治疗进展，由章建林撰写，可能探讨了当前在医学领域中与跨性别个体相关的外科手术新进展、技术改进以及对患者的效果评估。内容可能还包括医学案例研究或对不同治疗方案的比较分析。然而由于无法从PDF中提取内容，具体细节未知。
  type: document
  format: PDF Document
  size: 102237
  md5: 5b029398d273c58e55f93f145567eebd
  date: 未知
  archived: '2024-10-27 06:24:54'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 外科治疗
  - 医学进展
  - 易性癖
  - 章建林
  page: 易性癖的外科治疗进展_章建林_page.md
- name: 曼谷雨变性医生简介
  filename: 曼谷雨变性医生简介.docx
  description: 该文件是关于曼谷雨变性手术中心的医生及其提供的不同变性手术方案的详细介绍。文件中描述了几个主要医生的手术价格、住院时间、治疗细节及其优缺点，以及曼谷雨变性中心提供的全程服务。该中心为希望进行变性手术的人提供从手术预约到术后护理的全程服务，并强调其多年的合作经验和对泰国各大医院和医生的了解。
  type: document
  format: Microsoft Word Document (OpenXML)
  size: 1367600
  md5: fb5d4a384cc5a4221212cba29ccf6885
  date: 未知
  archived: '2024-10-27 06:24:54'
  link: ''
  creator: ''
  tags:
  - 变性手术
  - 医疗资源
  - 医生介绍
  - 泰国
  - 跨性别
  - 护理服务
  - 变性经历
  page: 曼谷雨变性医生简介_page.md
- name: 曼谷雨变性医生简介
  filename: 曼谷雨变性医生简介.pdf
  description: 这份文件详细介绍了泰国曼谷雨变性中心的变性手术服务，包括不同医生及手术方案的细节、价格、术后护理建议和中心的服务优势。文件中还对比了不同手术选择的敏感度、外形和费用，提供了详细的参考信息供有需要的人士考虑选择合适的手术医生及方案。
  type: document
  format: PDF Document
  size: 6991389
  md5: cb2d0195a6d2b1bc5840856bc55d9c90
  date: 未知
  archived: '2024-10-27 06:24:54'
  link: ''
  creator: ''
  tags:
  - 曼谷雨变性中心
  - 变性手术
  - 医疗服务
  - 术后护理
  - 泰国医生
  - 价格比较
  - 跨性别
  - 变性经验分享
  page: 曼谷雨变性医生简介_page.md
- name: 泰国手术指导
  filename: 泰国手术指导.pdf
  description: 这份文档是关于赴泰国进行性别确认手术的指导指南。作者更新了手术前的准备工作，包括护照、现金和签证要求。此外，还提供了在曼谷的基本交通信息，以及对手术医生的建议。文档中还强调了手术的费用和相关注意事项。
  type: document
  format: PDF Document
  size: 214124
  md5: d4d9dbdc8eb4f5dc0f04143daebe0afc
  date: 未知
  archived: '2024-10-27 19:06:01'
  link: ''
  creator: ''
  tags:
  - 泰国手术
  - 跨性别健康
  - 性别确认手术
  - 国际医疗指南
  page: 泰国手术指导_page.md
- name: 男_女易性癖外科治疗中具有性感觉功能的阴蒂再造_陈焕然
  filename: 男_女易性癖外科治疗中具有性感觉功能的阴蒂再造_陈焕然.pdf
  description: 该文件是关于从男性到女性易性癖转变过程中，重新构造具有良好的形态和性感觉功能的阴蒂的外科治疗方法的研究。文中详细描述了一种新的阴蒂再造术，包括手术步骤、血管神经解剖特点以及术后效果评估。该研究由陈焕然和陈宗基进行，其成果应用于实际临床病例。
  type: document
  format: PDF Document
  size: 347724
  md5: 4cf32b5a5b5ff2035555c44ebd3974f5
  date: '1995'
  archived: '2024-10-27 06:24:54'
  link: ''
  creator: ''
  tags:
  - 阴蒂再造
  - 跨性别外科
  - 性感觉功能
  - 医学研究
  - 男到女易性癖
  page: 男_女易性癖外科治疗中具有性感觉功能的阴蒂再造_陈焕然_page.md
- name: 男变女阴道成形术失败再行腹腔镜下回肠代阴道成形术1例
  filename: 男变女阴道成形术失败再行腹腔镜下回肠代阴道成形术1例.pdf
  description: 这是一份关于一例男变女性别重置手术，具体为阴道成形术失败后采用腹腔镜辅助回肠代阴道成形术的医学案例报告。文章记录了患者术前和术后的详细病情与治疗过程，并对变性手术作为性别认知障碍治疗手段进行了讨论。
  type: document
  format: PDF Document
  size: 2007095
  md5: 3b9230024ac2afe2186e484040430d0f
  date: 2011-07
  archived: '2024-10-27 06:24:54'
  link: ''
  creator: ''
  tags:
  - 变性手术
  - 阴道成形术
  - 腹腔镜手术
  - 回肠代阴道成形
  - 医学案例
  - 易性癖
  - 性别重置手术
  page: 男变女阴道成形术失败再行腹腔镜下回肠代阴道成形术1例_page.md
- name: 男女变性手术的护理15例
  filename: 男女变性手术的护理15例.pdf
  description: 该文件详细介绍了针对15例男—女变性手术患者的护理经验和过程。内容涵盖术前心理护理、术后恢复过程中的引流管和伤口管理、内分泌失调护理以及患者出院后的指导。研究主要基于北京中国医学科学院整形外科医院性别重塑中心的数据，提供了易性癖患者在变性手术过程中的详细护理方案和注意事项。
  type: document
  format: PDF Document
  size: 208956
  md5: b8987f9be75068b7c08b3f541e00c47b
  date: 2023年
  archived: '2024-10-27 06:24:54'
  link: ''
  creator: ''
  tags:
  - 男—女变性手术
  - 护理经验
  - 心理护理
  - 内分泌失调
  - 北京
  - 易性癖
  page: 男女变性手术的护理15例_page.md
- name: 男性易性癖的心理护理探讨
  filename: 男性易性癖的心理护理探讨.pdf
  description: 本文探讨了男性易性癖患者的心理护理方法及其有效性，旨在帮助患者克服心理障碍并取得心理平衡。文章通过对两例男性易性癖患者的心理护理进行分析，讨论了社会文化因素对患者治疗的影响，并提出尊重和接纳自我的重要性。
  type: document
  format: PDF Document
  size: 26823
  md5: f5894d0f5284e5641ab3a8469c852b20
  date: '1995'
  archived: '2024-10-27 06:24:54'
  link: ''
  creator: ''
  tags:
  - 心理护理
  - 易性癖
  - 性别认同障碍
  - 心理健康
  - 通过过渡经历
  page: 男性易性癖的心理护理探讨_page.md
- name: 走进性别重塑中心重新认识性别——访中国医学科学院整形外科医院性别重塑中心首席专家陈焕然博士
  filename: 走进性别重塑中心重新认识性别——访中国医学科学院整形外科医院性别重塑中心首席专家陈焕然博士.pdf
  description: 该文件是关于中国医学科学院整形外科医院性别重塑中心的首席专家陈焕然博士的专访，探讨性别认知与重塑的议题。陈博士介绍了当代社会对性别的新认识，以及他在性别重塑手术领域的经验与心得。他还分享了一些患者的真实故事，揭示了易性癖患者的心理困扰与社会挑战。
  type: document
  format: PDF Document
  size: 1133665
  md5: fdbe9d47b7c7b5efe311480409dc1ac5
  date: 未知
  archived: '2024-10-27 06:24:53'
  link: ''
  creator: ''
  tags:
  - 性别重塑
  - 易性癖
  - 性别认知
  - 医疗经验
  - 专访
  - 陈焕然
  page: 走进性别重塑中心重新认识性别——访中国医学科学院整形外科医院性别重塑中心首席专家陈焕然博士_page.md
- name: 跨性别安全指南
  filename: 跨性别安全指南.pdf
  description: 这个文件是一本关于跨性别者如何在日常生活中保护个人隐私和安全的指南。内容涵盖了使用手机、个人电脑以及与家人相处时的安全措施。此外，它详细介绍了如何保护个人信息，防止数据泄漏，并在必要时寻求安全援助的方法。
  type: document
  format: PDF Document
  size: 1665453
  md5: b04710ff9e2b7ae6c2300c8f87c34460
  date: 未知
  archived: '2024-10-27 06:25:35'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 隐私保护
  - 安全指南
  - 手机安全
  - 信息安全
  page: 跨性别安全指南_page.md
- name: 阴囊皮瓣结合黏膜／皮肤微粒法再造阴道在男变女变性手术中的应用
  filename: 阴囊皮瓣结合黏膜／皮肤微粒法再造阴道在男变女变性手术中的应用.pdf
  description: 该文档详细介绍了一种结合阴囊皮瓣和黏膜/皮肤微粒法的男变女阴道再造手术技术。文章分析了该技术的优点和缺点，探讨了其在再造宽敞润滑的阴道以及逼真外阴形态方面的效果，认为这种方法值得临床推广。
  type: document
  format: PDF Document
  size: 260246
  md5: 852711ac961b27e47f672f597531c6f3
  date: 2014-09
  archived: '2024-10-27 06:24:53'
  link: ''
  creator: ''
  tags:
  - 变性手术
  - 阴道再造
  - 医疗技术
  - 跨性别女性
  - 医学研究
  page: 阴囊皮瓣结合黏膜／皮肤微粒法再造阴道在男变女变性手术中的应用_page.md
- name: 阴茎阴囊皮瓣在男变女变性术中的应用
  filename: 阴茎阴囊皮瓣在男变女变性术中的应用.pdf
  description: 该文章讨论了阴茎阴囊皮瓣在男变女变性术中的应用。研究涵盖1996至2010年期间，在荒南省郸城县人民医院进行的14例手术病例，使用阴茎阴囊皮瓣再造阴道、外阴，并用部分龟头组织重建阴蒂。结果表明，大多数患者对再造的器官形态和功能表示满意，术后并发症较少。
  type: document
  format: PDF Document
  size: 732738
  md5: 4b2b84d90acc980ab84d77152a9840fe
  date: 2012-10
  archived: '2024-10-27 06:24:53'
  link: ''
  creator: ''
  tags:
  - 变性手术
  - 男变女
  - 医学研究
  - 阴道重建
  - 阴蒂再造
  - 阴茎阴囊皮瓣
  - 案例研究
  page: 阴茎阴囊皮瓣在男变女变性术中的应用_page.md
- name: 阴蒂成形术11例报告_邢新
  filename: 阴蒂成形术11例报告_邢新.pdf
  description: 这是一篇来自《中华整形外科杂志》2001年5月刊的研究报告，重点介绍了阴蒂成形术在11例患者中的应用。研究对象包括严重男性化的女性假两性畸形患者、误养女性的男性假两性畸形患者、男性易性癖者以及Klinefelter综合征患者。报告详细描述了使用带阴蒂或阴茎背血管神经蒂的组织移植方法进行的阴蒂重建术，所有病例术后效果良好。
  type: document
  format: PDF Document
  size: 144333
  md5: 97b8d23cb965b900c4440ff66ca12115
  date: 2001-05
  archived: '2024-10-27 06:24:53'
  link: ''
  creator: ''
  tags:
  - 性别重置手术
  - 两性畸形
  - 阴蒂成形术
  - 跨性别医疗
  - Klinefelter综合征
  page: 阴蒂成形术11例报告_邢新_page.md
subdirs:
- suporn手术
