name: 法律法规与政府文件
description: 本目录收录与跨性别相关的法律法规和政府文件，涵盖变性手术、性别变更、以及与跨性别权利和医疗相关的政策文件。这些文件对于跨性别人士的合法权益和社会接纳程度具有重要意义。
curator: ''
source: ''
tags:
- 法律法规
- 政府文件
- 跨性别权利
- 性别认同
- 社会政策
license: ''
files:
- name: 09__变性手术技术管理规范征
  filename: 09__变性手术技术管理规范征.pdf
  description: 本文件为《变性手术技术管理规范征》草案，旨在规范变性手术的技术要求与管理流程。文中详细探讨了手术的适应症、禁忌症，手术方式，术前评估与准备，以及术后护理等方面。该规范的制定目的是为了保障变性手术的安全性与有效性，提升医疗服务的标准，确保患者的知情权与选择权。此外，文中强调了医务人员在手术过程中应遵守的伦理规范与法律法规，确保对所有跨性别者的尊重与支持。
  type: document
  format: PDF Document
  size: 466420
  md5: 3dea8d62c04b66060c8afbaf4febffa0
  date: 未知
  archived: '2024-11-01 18:59:26'
  link: https://www.cma.org.cn/attachment/2009/11/27/20091127677c696e62fa47609683657a602a917c.pdf
  creator: ''
  tags:
  - 变性手术
  - 医疗规范
  - 跨性别权利
  - 法律法规
  - 手术管理
  - 患者权益
  page: 09__变性手术技术管理规范征_page.md
- name: 2__变性手术_按已下发规定执行
  filename: 2__变性手术_按已下发规定执行.pdf
  description: 该文件详细阐述了变性手术的相关法律法规，包括手术在医疗体系中的地位、要求及申请流程等内容。文件中可能包含对变性手术的政策指导，手术费用的报销机制，以及变性人群在医疗服务中的合法权益保护。此外，文件旨在为医疗机构和相关人员提供法律依据，以确保手术的合规操作。文件中提到政府已经发布了实施变性手术的具体规定，强调法律和医疗标准对于维护跨性别人士的健康和社会保障的重要性。
  type: document
  format: PDF Document
  size: 846716
  md5: f65e050584da608371edf3c7f8141b79
  date: 未知
  archived: '2024-11-01 18:59:26'
  link: https://www.qiluhospital.com/site75/cyxz/images/2012/11/01/2C72DDF5D733DF9F5F8503D31C4528B2.pdf
  creator: ''
  tags:
  - 变性手术
  - 法律法规
  - 医疗资源
  - 跨性别权益
  - 政策指导
  page: 2__变性手术_按已下发规定执行_page.md
- name: 性别变更更正办理服务指南
  filename: 性别变更更正办理服务指南.pdf
  description: 该文件是《性别变更更正办理服务指南》，详细说明了在山西省办理性别变更的相关规定和条件。指南适用于辖区内的常住户籍人口，并说明了申请的审查类型为即审即办，受理和决定机构均为公安派出所。申请人因变性手术后需要更改户籍登记性别的，需提出书面申请，并提供相应的申请材料，包括户口簿、身份证及性别鉴定证明等。指南还列出了网上申请和现场申请的基本流程和方法，以及办结时限与办公时间信息，为跨性别人士提供了实用的政策参考。
  type: document
  format: PDF Document
  size: 134382
  md5: 999c6055a38b260861819b3787d59385
  date: 未知
  archived: '2024-10-30 07:09:45'
  link: http://www.huguan.gov.cn/hgxgk/zfxxgk/zwgk/hjglly/zdjsxmlygknr/gxzhjglnr/lqz/202012/P020220815575849147443.pdf
  creator: ''
  tags:
  - 性别变更
  - 跨性别
  - 法律指南
  - 社区服务
  - 山西省
  - 户籍登记
  page: 性别变更更正办理服务指南_page.md
- name: 性别选择权性质界定与法权塑造
  filename: 性别选择权性质界定与法权塑造.pdf
  description: 本文探讨了性别选择权的性质及其法权塑造，共分为几个主要部分。首先，定义了性别选择权，指出其是指行为人因生理差异或性别焦虑原因依法自主变更为另一目标性别的权利。承认性别选择权有助于主体资格建构与确证、身份关系认证、婚姻关系缔结和社会角色识别。此外，文中详细分析了性别选择权的法律基础，包括自然法、宪法以及民法的相关规定，从国际到国内的发展情况被逐一梳理。尤其提到德国、英国等国家在性别选择权的立法与实际案例中所取得的进展和面临的挑战。最后，针对权利的行使条件，包括年龄、婚姻状态、精神医疗要求等，进行了深入的探讨，强调法律应当尊重和保障每个人的性别选择权，确保其与个人尊严和人身权利相一致。
  type: document
  format: PDF Document
  size: 407696
  md5: d90b25c38feb91d7e8248f89dac4be2c
  date: '2018-03-01'
  archived: '2024-11-01 09:18:36'
  link: https://www.civillaw.com.cn/uploadfile/lmpic/20180315/20180315200557734.pdf
  creator: ''
  tags:
  - 性别选择权
  - 法律文献
  - 跨性别权利
  - 人权
  - 社会角色
  - 民法
  - 性别身份
  - 法律政策
  page: 性别选择权性质界定与法权塑造_page.md
- name: 户籍管理领域基层政务公开标准目录
  filename: 户籍管理领域基层政务公开标准目录.pdf
  description: 该文件为《户籍管理领域基层政务公开标准目录》，包含了关于公民户籍管理政策的具体信息，如出生登记、死亡注销、性别变更、民族成份登记等各项基层政务公开内容。文件中详细列出了不同类型的公开事项、对应的受理部门及所需材料，以及每项业务的办理流程、时限和收费标准，旨在提供透明的政务服务，并确保公民能够顺利完成各种户籍相关的申请和变更。该目录中还包括了对于跨性别人士在申请性别变更过程中需要提供的材料和流程，反映了相关法律法规对跨性别者权益的保障。
  type: document
  format: PDF Document
  size: 209839
  md5: ea9b84b452f3320a701119ed085ded81
  date: 未知
  archived: '2024-10-30 06:37:43'
  link: http://www.cnyc.gov.cn/upload-service/2c90808483d171790183e4d0219b0002/2c90808483d171790183e8b166ee0005/WY1598608411929481216.pdf
  creator: ''
  tags:
  - 户籍管理
  - 跨性别
  - 法律法规
  - 政务公开
  - 性别变更
  - 出生登记
  - 死亡注销
  - 社会政策
  page: 户籍管理领域基层政务公开标准目录_page.md
- name: 联合国秘书长报告_应对不平等现象，重新走上到2030_年消除艾滋病的轨道
  filename: 联合国秘书长报告_应对不平等现象，重新走上到2030_年消除艾滋病的轨道.pdf
  description: 本文件为联合国秘书长于2021年3月31日提交的报告，旨在系统性地分析全球艾滋病防治进展及存在的挑战。报告进一步强调在实现2020年全球抗击艾滋病目标未能达成的背景下，针对艾滋病毒/艾滋病的政治承诺需要重新审视与加强，并指出艾滋病在许多群体中仍然是一个充满不平等的流行病。报告中提到，性别不平等、社会边缘化、对重点人群的污名化等因素继续阻碍艾滋病毒防治工作。在提出到2030年消除艾滋病的可持续发展目标时，报告列出了未来五年的详细战略目标，明确需要采取紧急的改革行动以结束不平等现象、加大投资以支持艾滋病毒的防治及卫生系统的韧性。本文件对于了解当前艾滋病全球防治的政策背景、社会影响及未来的行动计划具有重要价值。
  type: document
  format: PDF Document
  size: 855729
  md5: b9912df81f1babc396ead13f72bcb803
  date: '2021-03-31'
  archived: '2024-11-01 19:11:32'
  link: http://hkb980dd.pic44.websiteonline.cn/upload/A-75-836_zh.pdf
  creator: ''
  tags:
  - 艾滋病
  - 防治政策
  - 不平等现象
  - 性别暴力
  - 重点人群
  - 社会保障
  - 联合国报告
  - 健康权利
  - 人际关系
  - 社会环境
  page: 联合国秘书长报告_应对不平等现象，重新走上到2030_年消除艾滋病的轨道_page.md
- name: 跨性别证件修改手册
  filename: 跨性别证件修改手册.pdf
  description: 本文件为《跨性别证件修改手册》，由彩虹律师团撰写并于2019年9月28日发布。手册详细介绍了跨性别者如何修改身份证、户口本、学历证书及资格证书中的性别信息，涵盖法律依据、申请所需材料、申请程序及相关案例。手册首先提供了名词解释，包括学历证书及学信网的概念，然后系统阐述了修改身份证和户口本的性别信息的法律基础和所需材料。此外，手册明确了修改学历证书和资格证书性别信息的相关规定，并提供了具体的申请流程与注意事项。手册的目的在于帮助跨性别者及其支持者了解相关法律政策，维护自己的合法权益，推动法律与政策的改善。
  type: document
  format: PDF Document
  size: 10046170
  md5: 88fa0af4a97084f72f3693b8a8bedeb0
  date: '2019-09-28'
  archived: '2024-10-30 06:37:01'
  link: https://docs.transonline.org.cn/files/%E8%B7%A8%E6%80%A7%E5%88%AB%E8%AF%81%E4%BB%B6%E4%BF%AE%E6%94%B9%E6%89%8B%E5%86%8C.pdf
  creator: ''
  tags:
  - 跨性别
  - 性别证件修改
  - 法律政策
  - 学历证书
  - 资格证书
  - 社会环境
  - 性别认同
  - 彩虹律师团
  page: 跨性别证件修改手册_page.md
subdirs: []
