name: 传统报纸与杂志
description: 本目录收录来自传统报纸与杂志的跨性别相关报道，涵盖变性经历、法律问题以及社会对跨性别者的态度等方面，展示了跨性别个体在社会中的生存现状和转变过程。
curator: ''
source: ''
tags:
- 新闻
- 跨性别
- 社会
- 变性经历
- 法律政策
- 媒体报道
- 生命故事
license: ''
files:
- name: 14__使他从孝子变性为孝女
  filename: 14__使他从孝子变性为孝女.pdf
  description: 本文记录了一位名叫刘霆的道德模范在进行变性手术过程中的心理历程与社会反响。刘霆由于背负着照顾尿毒症母亲的责任而备受关注，他的变性决定引发了社会的广泛讨论。文章探讨了传统价值观与个人选择之间的冲突，指出尽管刘霆的决定符合个人的追求，但在某些人的眼中，这种行为被视为‘离经叛道’。在变性手术前，刘霆为了追求身心的统一，付出了极大的代价，甚至一度面临心理压力和社会的流言蜚语。本文旨在表达对变性人士的理解与支持，呼吁社会应对跨性别者展现更多的同情与宽容。
  type: document
  format: PDF Document
  size: 328847
  md5: 2a9add42264f120759ecc495c2940d4d
  date: 未知
  archived: '2024-10-30 06:46:12'
  link: http://www.zhld.com/zkwb/page/1/2014-08-18/02/96101408294625949.pdf
  creator: ''
  tags:
  - 跨性别
  - 变性手术
  - 道德模范
  - 心理压力
  - 家庭责任
  - 社会反响
  page: 14__使他从孝子变性为孝女_page.md
- name: 18岁男孩在快捷酒店里接受变性手术
  filename: 18岁男孩在快捷酒店里接受变性手术.pdf
  description: 该文件记录了一名18岁男孩小斌在快捷酒店通过非法途径接受变性手术的经过。手术由他在网上结识的自称经验丰富的‘医生’小俊进行，实际操作是在酒店房间内进行的，且手术所需技巧来源于网上观看视频。小斌早在初中时期就开始有变性意识，并多次服用雌性激素以准备变性手术。由于家庭因素，小斌未能告知父母自己的真实想法，当被发现后，其父母惊慌失措并报了警。最终，因小俊未取得医生执业资格，检察院对其以涉嫌非法行医罪提起公诉。
  type: document
  format: PDF Document
  size: 1689844
  md5: 6ce509f72ab91e5c526d0712891bd2c6
  date: 2018年5月
  archived: '2024-10-30 06:45:36'
  link: http://zjfzb.zjol.com.cn/images/2018-08/30/f2018083000016.pdf
  creator: ''
  tags:
  - 跨性别
  - 变性手术
  - 非法行医
  - 青春期
  - 家庭关系
  - 医疗资源
  - 法律问题
  page: 18岁男孩在快捷酒店里接受变性手术_page.md
- name: 他们在家门口书写生命终章
  filename: 他们在家门口书写生命终章.pdf
  description: 本文来自健康时报的第2118期，重点报道了跨性别医疗资源的发展，包括一位妇科医生开设的跨性别门诊。这篇文章展示了跨性别者在寻找医疗帮助时的期待与需求，并反映了当今社会对跨性别群体在医疗资源方面的逐渐重视。此外，文章中提到了一些创新的养老服务模式，尽管其重点在老年人群体，但提供的智能设备和服务模式也可以启发对于跨性别者的关怀支持。整体来看，本文不仅关注个人的生命故事与医疗经历，也触及社会政策与环境如何影响跨性别者的生活。
  type: document
  format: PDF Document
  size: 1543444
  md5: 2cef04069e6565dc23c620ca34932be2
  date: 2024年10月8日
  archived: '2024-10-30 06:45:51'
  link: http://paper.people.com.cn/jksb/pc/attachement/202410/08/ff7a36aa-e57b-4788-bec4-fdcab347980b.pdf
  creator: ''
  tags:
  - 跨性别医疗
  - 生命故事
  - 医疗资源
  - 社会政策
  - 跨性别者
  - 生存现状
  - 智能设备
  - 养老服务
  page: 他们在家门口书写生命终章_page.md
- name: 变性后利用色相行骗安徽变性第一人获刑三年
  filename: 变性后利用色相行骗安徽变性第一人获刑三年.pdf
  description: 该文件为一篇报道，详细讲述了一位名为韩美玲的女性的生活故事，围绕她的变性过程以及因诈骗罪而被判刑的经历。韩美玲原名韩俊岭，因自幼感觉与性别身份不符而选择进行变性手术，成为安徽的第一位变性女性。报道中提到，尽管她在变性后获得了媒体的高度关注与称赞，但其生活质量并未如预期改善。随着高额的生活开销和渴望物质的追求，她因经济压力而走上了违法道路，最终因诈骗和敲诈勒索罪被判处有期徒刑三年。这段故事揭示了跨性别者在社会中所面临的困境以及个人选择与法律之间的复杂关系。
  type: document
  format: PDF Document
  size: 1686719
  md5: 561f296b9ea18e799df3ee558ea683cf
  date: 未知
  archived: '2024-10-30 06:45:51'
  link: http://www.ahscb.com.cn/page/1/2014-12/08/07/2014120807_pdf.pdf
  creator: ''
  tags:
  - 跨性别
  - 变性经历
  - 社会环境
  - 法律案件
  - 诈骗
  - 个人故事
  page: 变性后利用色相行骗安徽变性第一人获刑三年_page.md
- name: 国外一准变性人参加男足
  filename: 国外一准变性人参加男足.PDF
  description: ''
  type: document
  format: PDF Document
  size: 3704285
  md5: d5a43109f2cb172ad84e8c6f5e78a07a
  date: ''
  archived: '2024-11-01 21:20:25'
  link: https://zzwb.zynews.cn/page/2/2014-05/07/A30/20140507A30_pdf.PDF
  creator: ''
  tags: []
  page: 国外一准变性人参加男足_page.md
- name: 夫拉客妻卖淫
  filename: 夫拉客妻卖淫.pdf
  description: 这份文件讲述了张莎的变性经历和生活故事。张莎原名张沙，在经历了诸多挑战和困扰后，决定进行变性手术，成为中国大陆第一位公开的变性人。文件详细描述了她的成长背景，包括出生在一个军人家庭的成长经历及对性别认同的困惑。张莎在社会上遭遇了种种歧视和困难，但最终选择了追求自己的真实自我，并勇敢分享自己的故事。她也谈及了对家庭的期望和最终移居香港的经历，以及在生活与感情上的挑战与坚持。文中涉及张莎在进行变性手术前的心理状态、手术后的生活选择，以及对社会环境变化的感受，以期引起人们对跨性别群体的理解与关注。
  type: document
  format: PDF Document
  size: 9749531
  md5: a02001c63a6e3dfb65df0ae533a8536e
  date: '2003-04-21'
  archived: '2024-10-30 06:45:51'
  link: http://szb.sxworker.com/Img/2003/10/SXGRB2003102104.pdf
  creator: ''
  tags:
  - 变性人
  - 性别认同
  - 个人故事
  - 变性手术
  - 社会歧视
  - 跨性别
  - 生存经历
  page: 夫拉客妻卖淫_page.md
- name: 对变性人该关注什么_-_中国妇女报_-_2004
  filename: 对变性人该关注什么_-_中国妇女报_-_2004.pdf
  description: 该文件是2004年《中华人民共和国妇女报》的一篇文章，标题为《对变性人该关注什么》。文章探讨了媒体对变性人的关注及报道现状，指出媒体在报道变性事件时缺乏对变性人内心世界的深入挖掘。文章提到，尽管社会对变性人的接受度提升，但仍有不少报道呈现猎奇与窥私心理，而非客观反映变性人的生活与挑战。文中提到了一些个案，例如某变性人因婚姻失败决心进行变性，和追求成为女模特的跨性别者。这些案例反映出社会文化因素对个体决策的影响，同时也引发了对变性手术风险和变性人生活质量的深刻思考。
  type: document
  format: PDF Document
  size: 85020
  md5: 6116097118c6217267a13ce7879066d5
  date: '2004-04-14'
  archived: '2024-10-30 15:47:08'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 变性人
  - 媒体报道
  - 社会文化
  - 性别认同
  - 生命故事
  page: 对变性人该关注什么_-_中国妇女报_-_2004_page.md
- name: 法治时空
  filename: 法治时空.pdf
  description: 该文件为《法治时空》的一篇报道，文章主要讲述了一起有关跨性别者朱小琼的犯罪事件。朱小琼，一名在北京进行了变性手术的跨性别女性，在酒吧中以女性身份活动，在与网友王进见面时，联合同伙进行了一起抢劫。报道详细描述了事件的经过，包括朱小琼如何在网上勾引王进，并指示同伙实施暴力抢劫。此外，文章中提及了朱小琼的个人背景，以及警方在事件之后的处理情况，反映了社会对跨性别者的接受度及其法律地位。
  type: document
  format: PDF Document
  size: 842641
  md5: 2767d0d3ae0a123dfa9d2741e9e7a0b6
  date: 2010.5.25
  archived: '2024-10-30 06:43:43'
  link: http://zjfzb.zjol.com.cn/zjfz/resfile/2010-05-25/04/ZJFZ2010052504.pdf
  creator: ''
  tags:
  - 跨性别
  - 法律
  - 犯罪事件
  - 社会问题
  - 变性人
  - 媒体报道
  page: 法治时空_page.md
- name: 老太太买飞机改豪宅
  filename: 老太太买飞机改豪宅.pdf
  description: 该文档为2015年9月10日出版的新闻稿，主要包含两个主题。一方面，报道了一位女士购买和改装飞机作为豪宅的创意故事，展示了她如何将一架旧飞机改造成了理想的居住空间，细节描绘了飞机内部的环境和改装方法；另一方面，报道了一些关于学校干预措施的新闻，其中提到一所小学要求学生午休采用打坐，而非睡觉，校长认为能够提升学生的定力。这些报道反映了社会生活中的一些普通却新颖的尝试，及其引发的家长和孩子们的反应。
  type: document
  format: PDF Document
  size: 1606879
  md5: 37c7f0fa8ca465a235670151e53c791a
  date: '2015-09-10'
  archived: '2024-10-30 06:43:44'
  link: http://epaper.632news.com/xst/page/51/2015-09/10/13/2015091013_pdf.pdf
  creator: ''
  tags:
  - 跨性别
  - 社会新闻
  - 法律政策
  - 教育
  - 生活方式
  - 婚姻家庭
  - 艺术与文化
  - 医疗资源
  page: 老太太买飞机改豪宅_page.md
- name: 走上T台刘婷最美蝶变
  filename: 走上T台刘婷最美蝶变.pdf
  description: 该文件是一篇关于刘婷的报道，详细讲述了她的生活故事与变化经历。刘婷是一名跨性别女性，她在2015年9月参加了一场全国性的选美大赛，赛事中成功获得了“最美蝶变奖”。她的故事吸引了不少媒体的关注，报道中提到她在经历变性手术后的心理变化，以及面对社会争议的勇气。刘婷提到，参加比赛的初衷是想要展示自己的变化，获得他人的理解和接受。内容中还提到刘婷在安检口遇到的困难，她展示了自己的新身份证，经历了一番麻烦后才顺利通过。文件中对刘婷进行了深度采访，包括她的过渡经历、对比赛结果的期望和对未来的展望。整体上，这篇报道展现了跨性别人士在社会中追求认同与尊重的艰辛与努力。
  type: document
  format: PDF Document
  size: 2283814
  md5: ad4adad9db1001df01021cbbe4e5591c
  date: '2015-09-24'
  archived: '2024-10-30 06:45:51'
  link: http://epaper.dbcsq.com/html/1/2015-09/24/A13/20150924A13_pdf.pdf
  creator: ''
  tags:
  - 跨性别
  - 选美比赛
  - 刘婷
  - 生命故事
  - 社会环境
  - 变性手术
  - 勇敢追求自我
  - 抗争与认可
  page: 走上T台刘婷最美蝶变_page.md
subdirs: []
