name: 心理
description: 本目录包含关于跨性别者心理健康的研究和经验分享，探讨了心理咨询与积极心理疗法在跨性别群体中的应用，以及与变性手术相关的心理护理内容。
curator: ''
source: ''
tags:
- 心理健康
- 跨性别者
- 心理咨询
- 变性手术
- 性别认同
- 心理疗法
license: ''
files:
- name: A_Systematic_Review_of_Research_on_Counselling_and
  filename: A_Systematic_Review_of_Research_on_Counselling_and.pdf
  description: 本文件是一篇关于为跨性别、女同性恋、男同性恋及双性恋人群提供咨询与心理治疗的系统综述。这项研究由多位来自伦敦大学学院及其他院校的教授及研究人员完成，于2007年首次发布。该文为从事心理健康服务的专业人士提供了重要的参考资料和分析。
  type: document
  format: PDF Document
  size: 775429
  md5: 675e99e42f2a167080bf2a98addc0441
  date: '2007-04-01'
  archived: '2024-10-27 19:06:58'
  link: ''
  creator: ''
  tags:
  - 系统综述
  - 心理治疗
  - 咨询
  - LGBT
  - 跨性别
  - 心理健康
  - 研究资料
  page: A_Systematic_Review_of_Research_on_Counselling_and_page.md
- name: Affirmative_Psychotherapy_with_Bisexual_Transgender_People
  filename: Affirmative_Psychotherapy_with_Bisexual_Transgender_People.pdf
  description: 本文讨论了为双性恋跨性别者提供积极心理治疗的方法，旨在提高心理健康服务对这一群体的包容性和有效性。作者Nick Embaye在文章中探讨了特定的心理疗法策略及其对改善双性恋跨性别者心理健康的意义。
  type: document
  format: PDF Document
  size: 772212
  md5: 6a230d7e365becc49b0c40e78b4d2f00
  date: '2006'
  archived: '2024-10-28 00:01:33'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 双性恋
  - 心理治疗
  - 心理健康
  - 包容性护理
  page: Affirmative_Psychotherapy_with_Bisexual_Transgender_People_page.md
- name: Depth_psychotherapy_with_transgender_people
  filename: Depth_psychotherapy_with_transgender_people.pdf
  description: 这篇文章介绍了一种用于跨性别人士的深层心理治疗初级模型。文章结合了现代心理动力学、荣格理论和性别认同理论，反映了跨性别身份发展的独特道路。它不将跨性别身份视为病态，而是探讨了跨性别个体在身份构建过程中由于社会误解和性别二元性带来的心理挑战。文章讨论了跨性别身份发展过程中的不同阶段，并提出了可能的治疗主题和干预措施，并通过作者37年的临床经验中的案例进行说明。
  type: document
  format: PDF Document
  size: 249774
  md5: 9d934b398276fdf6b83547bdd8ce83e3
  date: 2009-05
  archived: '2024-10-28 00:01:33'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 心理治疗
  - 性别认同
  - 心理动力学
  - 荣格理论
  page: Depth_psychotherapy_with_transgender_people_page.md
- name: 儿童及青少年精神心理异常问题
  filename: 儿童及青少年精神心理异常问题.pdf
  description: 该文件为一份关于儿童及青少年精神心理异常问题的研究文档，特别聚焦于性别烦躁（Gender Dysphoria）的定义、临床表现、诊断标准与治疗方法。文中详细阐讨了儿童和青少年如何体验和表达与其生理性别不一致的性别身份，以及此状况对他们的心理和社会功能造成的影响。文件还说明了DSM-IV-TR与DSM-5在性别认同障碍的诊断名称上的变化，标志着对性别认同的去病化与多元认可。该文档还探讨了性别烦躁的患病率，各年龄段的临床表现，尤其是性激素治疗与变性手术的必要性和过程，以及与其他精神心理障碍的鉴别与共病情况。
  type: document
  format: PDF Document
  size: 568676
  md5: bf5f507f230feefc1fe4fd906e4a0066
  date: 未知
  archived: '2024-11-01 09:19:09'
  link: https://www.mhealthu.com/uploads/20200313/1654d2f111cef626e4c4ea9a0f0e711e.pdf
  creator: ''
  tags:
  - 儿童
  - 青少年
  - 精神心理
  - 性别烦躁
  - 性别认同
  - 医疗资源
  - 治疗方法
  - 心理健康
  - 法律政策
  - 社会支持
  page: 儿童及青少年精神心理异常问题_page.md
- name: 全国心理援助热线机构联系信息心理服务与援助机构
  filename: 全国心理援助热线机构联系信息心理服务与援助机构.pdf
  description: 本文件包含全国各地心理援助热线及心理服务机构的联系信息，提供心理咨询、危机干预及法律援助等服务。文件详细列举了多家位于不同地区的NGO机构，包括机构名称、所在地、性质、联系方式和服务简介。例如，‘12355’青少年服务台致力于为青少年提供心理咨询与法律咨询援助，‘阳光工程心理互助论坛’旨在帮助抑郁症患者并普及相关知识。此外，还有针对性侵害及家庭暴力的服务机构提供热线、法律支持和心理辅导。该文件为需要心理帮助的人士提供了重要的资源信息，涵盖了广泛的主题，包括心理健康、性别暴力、家庭暴力反对及性少数群体的支持等。
  type: document
  format: PDF Document
  size: 311496
  md5: 0ba65b9d7a6e24147eb7e5a5a3ec3e06
  date: 未知
  archived: '2024-11-01 19:03:38'
  link: https://xinli.buct.edu.cn/_upload/article/files/d1/86/58119f32496fb1e0e7b64d368a1e/b6b8a434-274d-41fd-b88e-e0bbdf430944.pdf
  creator: ''
  tags:
  - 心理援助
  - 热线
  - 心理服务
  - 危机干预
  - 法律支持
  - 性别暴力
  - 家庭暴力
  - 性少数群体
  - 跨性别
  - 心理健康
  page: 全国心理援助热线机构联系信息心理服务与援助机构_page.md
- name: 变性手术患者的心理护理
  filename: 变性手术患者的心理护理.pdf
  description: 此文档探讨变性手术患者的心理护理，介绍了对易性癖患者在术前和术后所需的心理支持和护理措施。文章强调了护理人员通过倾听、交流和尊重患者个性的重要性，以帮助患者更好地适应手术及其后的生活。报告基于对14例实施变性手术的患者的观察和护理实践。
  type: document
  format: PDF Document
  size: 259056
  md5: f6b09478cb9fecdcac349aab2472847b
  date: '2002-06-01'
  archived: '2024-10-27 06:27:22'
  link: ''
  creator: ''
  tags:
  - 变性手术
  - 心理护理
  - 易性癖
  - 性别认同
  - 临床护理
  page: 变性手术患者的心理护理_page.md
- name: 從「性別認同障礙」到「性別不安」
  filename: 從「性別認同障礙」到「性別不安」.pdf
  description: 本文件分析了性别认同相关诊断从DSM-IV中的"性别认同障碍"转变为DSM-5中的"性别不安"的过程，并探讨了其去病化的意义。文中详细讨论了该变更对于跨性别群体的影响，以及性别认同的多样性和其正常化的必要性。此外，文件中还包括跨性别健康专专业学会对新诊断标准的反响，并讨论了对成人与儿童性别不安诊断的独立和伦理考量。
  type: document
  format: PDF Document
  size: 1053324
  md5: 89f771669a22ee003e70cbe9bc0192a6
  date: '2013'
  archived: '2024-10-27 06:27:23'
  link: ''
  creator: ''
  tags:
  - 性别认同
  - 性别不安
  - DSM-5
  - 跨性别
  - 去病化
  - 心理健康
  - 性别多样性
  - 医疗诊断
  - 精神医学
  page: 從「性別認同障礙」到「性別不安」_page.md
- name: 性别烦躁的诊断和治疗
  filename: 性别烦躁的诊断和治疗.pdf
  description: 该文献探讨了性别烦躁的诊断与治疗，目的是增强医务工作者对这一疾病的认识与重视。性别烦躁是一种个体强烈确认自己为相反性别并感受到痛苦的状态，往往源自生理性别与自我认同性别之间的不匹配。文章中明确指出性别烦躁可以在儿童期、青春期或成年期出现，并且青少年及成年患者因身体发育而感受到的烦躁可能更加明显。治疗方法因年龄层和具体情况而异，儿童和青少年主要采用心理支持和家庭治疗，而成年人则可以选择性激素治疗及手术干预。整体上，该文献不仅为医务工作者提供了有关性别烦躁的专业性解读，也呼吁社会对该群体的理解与支持。
  type: document
  format: PDF Document
  size: 656798
  md5: 444bd7c4f5f1c6bcb7fc6fb03d5e0645
  date: '2019-02-01'
  archived: '2024-11-01 09:19:44'
  link: https://www.mhealthu.com/uploads/enclosure/201907/201907291641401353480122.pdf
  creator: ''
  tags:
  - 性别烦躁
  - 心理治疗
  - 医疗资源
  - 跨性别
  - 诊断与治疗
  - 生存现状
  - 心理卫生
  page: 性别烦躁的诊断和治疗_page.md
- name: 性别认同障碍
  filename: 性别认同障碍.doc
  description: 这份档案涉及性别认同障碍，属于心理健康及医疗护理的主题。尽管文件内容无法提取，但可以推测该档案可能包含有关跨性别个体在性别认同障碍方面的心理健康问题、诊断标准、治疗途径及相关心理支持方法。
  type: document
  format: Microsoft Word Document
  size: 55808
  md5: 23f82f61eae1cbdc3478b0a43eec791a
  date: 未知
  archived: '2024-10-27 06:27:22'
  link: ''
  creator: ''
  tags:
  - 心理健康
  - 性别认同障碍
  - 跨性别
  - 医疗护理
  - 心理支持
  page: 性别认同障碍_page.md
- name: 性别认同障碍_人格_心理病理及社_省略_适应水平的术前术后变化的比较研究_Iris_Monteiro
  filename: 性别认同障碍_人格_心理病理及社_省略_适应水平的术前术后变化的比较研究_Iris_Monteiro.pdf
  description: 这篇文章是一项关于性别认同障碍（GID）患者在变性手术前后人格、心理病理和社会适应水平变化的比较研究。研究表明，受试者在手术后显现出多层次的显著变化，包括在人格档案、心理病理症状和社会适应性方面的积极演变。作者通过非随机样本调查22名性别认同障碍患者，采用了多种心理评估工具，结果指出变性手术对人格结构及基本人格模式带来的显著影响。
  type: document
  format: PDF Document
  size: 490637
  md5: 1aee369e2e71d46ba36f8283c0fa497b
  date: '2012-01-01'
  archived: '2024-10-28 00:01:33'
  link: ''
  creator: ''
  tags:
  - 性别认同障碍
  - 人格变化
  - 心理病理
  - 社会适应
  - 变性手术
  - 心理学研究
  page: 性别认同障碍_人格_心理病理及社_省略_适应水平的术前术后变化的比较研究_Iris_Monteiro_page.md
- name: 走出性别困境_跨性别_与_性别焦虑_的医疗援助_潘柏林_Z_Library
  filename: 走出性别困境_跨性别_与_性别焦虑_的医疗援助_潘柏林_Z_Library.pdf
  description: 本文件名为《走出性别困境：跨性别与性别焦虑的医疗援助》，由潘柏林编写。它涉及跨性别者在面临性别焦虑时的心理健康问题，并探讨了医疗系统可以如何为这些人群提供支持和帮助。文件可能包含对跨性别人士进行心理评估、治疗方案以及支持性资源的详细讨论，旨在为跨性别者提供专业的医疗援助建议。同时，它还可能强调跨性别者在治疗过程中所需的尊重与理解，以改善他们的生活质量和心理健康。
  type: document
  format: PDF Document
  size: 6491180
  md5: 316baeb18418346b2df22c676a31f9fe
  date: 未知
  archived: '2024-10-30 15:45:45'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 性别焦虑
  - 医疗援助
  - 心理健康
  - 生命故事与过渡经历
  - 经验分享
  page: 走出性别困境_跨性别_与_性别焦虑_的医疗援助_潘柏林_Z_Library_page.md
subdirs: []
