name: 其他
description: 该目录包含关于跨性别者在中国的健康护理及相关医疗资源的信息，特别是一些其他类型的支持和资源，不适合进行分类的资料。这些资料旨在帮助跨性别者更好地理解和获取所需的医疗信息与服务。
curator: ''
source: ''
tags:
- 健康护理
- 医疗资源
- 跨性别者
- 支持资源
- 中国
license: ''
files:
- name: -最新的HIV_临床研发数据驱动新一轮针对治疗预防和治愈的创新
  filename: -最新的HIV_临床研发数据驱动新一轮针对治疗预防和治愈的创新.pdf
  description: 本文件为2022年世界艾滋病大会的最新HIV临床研发数据驱动创新的报告。文件中提到，吉利德科学在会议上强调了科学创新与全球合作的重要性，并分享了针对HIV治疗、预防和治愈的最新科研数据。报告也提到吉利德在与HIV社区合作方面的努力，特别是通过多个项目来改善受HIV影响个体的健康成果。此外，文件详细列出了多项HIV治疗、预防研究的最新进展，包括针对初治HIV感染者的研究和对新型药物的耐药性分析。
  type: document
  format: PDF Document
  size: 5795740
  md5: 7d11ca4fda939cbef3a0730d02901932
  date: '2022-07-21'
  archived: '2024-10-30 06:42:52'
  link: https://gileadchina.cn/-/media/gilead-china/pdfs/news-and-press/press-releases/20200722-cn-adis-2022.pdf
  creator: ''
  tags:
  - HIV
  - 艾滋病大会
  - 吉利德科学
  - 临床研发
  - 治疗与预防
  - 科学创新
  - 健康平等
  - 跨性别健康
  page: -最新的HIV_临床研发数据驱动新一轮针对治疗预防和治愈的创新_page.md
- name: SOC_V7_Chinese
  filename: SOC_V7_Chinese.pdf
  description: 这份文件是世界跨性别健康专业协会（WPATH）发布的《跨性别及非性别常规者健康照护标准》的第七版中文翻译。文件详细介绍了健康照护的目标、适用性及相关策略，包括心理健康、贺尔蒙治疗、性别相关手术等多方面的指南。这是一个关于跨性别者健康照护的权威指南，涵盖了医疗、心理及生活质素等多方面的内容。
  type: document
  format: PDF Document
  size: 5733967
  md5: a56ef4c4d9e3b0a26bb1686b12d979c0
  date: '2012'
  archived: '2024-10-28 00:01:33'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 健康照护
  - WPATH
  - 医疗指南
  - 性别不安
  page: SOC_V7_Chinese_page.md
- name: 中国医患社会心态分问卷的跨性别测量等值性
  filename: 中国医患社会心态分问卷的跨性别测量等值性.pdf
  description: 本文件为《心理技术与应用》期刊中关于“中国医患社会心态分问卷的跨性别测量等值性”的研究论文，由姜鹤和赵礼撰写。研究旨在验证该问卷的因子结构，并检验在不同性别的医患群体之间的测量等值性。研究样本包括名医和患者，通过单组验证性因素分析及跨性别测量等值性检验，结果表明多个问卷在不同性别组间均具有可接受的测量等值性，进一步揭示了医患关系的满意度和健康观在性别差异中的表现。该研究为医患关系及其测量工具的性别适应性研究提供了实证支持，具有重要的临床和社会心理学意义。
  type: document
  format: PDF Document
  size: 616421
  md5: c6bef1149655263cc2761cbf4e5ee8af
  date: 未知
  archived: '2024-10-30 06:41:18'
  link: http://www.xljsyyy.com/CN/article/downloadArticleFile.do?attachType=PDF&id=440
  creator: ''
  tags:
  - 跨性别研究
  - 医患关系
  - 心理测量
  - 社会心态问卷
  - 性别等值性
  - 满意度评估
  page: 中国医患社会心态分问卷的跨性别测量等值性_page.md
- name: 中国易性症多学科诊疗专家共识
  filename: 中国易性症多学科诊疗专家共识.pdf
  description: 该文件为中国心理卫生协会性心理健康专业委员会发布的关于易性症的多学科诊疗专家共识。内容涵盖了易性症的评估、诊断和治疗，并提出了针对临床实践的建议和规范，以促进各学科的
    cooperación 和发展，旨在为相关专业人员提供更安全和有效的诊疗规范。
  type: document
  format: PDF Document
  size: 605157
  md5: e35e072de45846913f3646911f837a98
  date: '2022'
  archived: '2024-10-28 07:04:06'
  link: ''
  creator: ''
  tags:
  - 易性症
  - 诊断
  - 治疗
  - 多学科
  - 专家共识
  - 心理健康
  - 医疗资源
  page: 中国易性症多学科诊疗专家共识_page.md
- name: 功能性腹患者健康促进行为量表的汉化及信效度检验
  filename: 功能性腹患者健康促进行为量表的汉化及信效度检验.pdf
  description: 本文件为功能性腹患者健康促进行为量表的汉化及其信效度检验研究。该量表旨在评估功能性腹患者在健康促进方面的行为表现, 通过对量表的有效性和可靠性进行检验，提供客观的测评工具，以便于医疗工作者和研究人员在临床实践和研究中更好地评估患者的健康促进行为。虽然无法从PDF中提取具体文本信息，但可以推测，该研究可能涉及问卷设计、数据收集及分析方法等内容，并对跨性别患者的特定健康需求进行探讨。
  type: document
  format: PDF Document
  size: 146
  md5: 9fe3cb2b7313dc79bb477bc8fde184a7
  date: 未知
  archived: '2024-10-30 06:40:11'
  link: http://www.zjyfyxzz.com/CN/article/downloadArticleFile.do?attachType=PDF&id=2630
  creator: ''
  tags:
  - 功能性腹患者
  - 健康促进
  - 量表汉化
  - 信效度检验
  - 跨性别健康
  - 医疗资源
  - 研究资料
  page: 功能性腹患者健康促进行为量表的汉化及信效度检验_page.md
- name: 复星联合优越保医疗保险条款
  filename: 复星联合优越保医疗保险条款.pdf
  description: 本文件为《复星联合优越保医疗保险条款》，详细列出了保险责任的免除条款。根据条款第2.8节，保险公司将不承担因被保险人故意犯罪、饮酒后驾驶、斗殴、精神疾病、整形手术及其他多种情况导致的医疗费用。具体包括但不限于被保险人自杀、因既往症产生的医疗费用、怀孕及其相关并发症、先天性疾病等情况。此文件明确了多项责任免除，旨在为保险投保人提供透明的信息，使其了解在什么情况下保险公司不承担责任。
  type: document
  format: PDF Document
  size: 170518
  md5: 9640dbced4922cc950148cb737a3e642
  date: 未知
  archived: '2024-10-30 06:41:44'
  link: https://resource.kaixinbao.com/eriskfile/escapeBlame/226101031_00011838.pdf
  creator: ''
  tags:
  - 医疗保险
  - 条款
  - 责任免除
  - 保险政策
  - 跨性别医疗资源
  - 医疗费用
  - 复星联合
  page: 复星联合优越保医疗保险条款_page.md
- name: 女女性接触者群体及艾滋病相关危险行为
  filename: 女女性接触者群体及艾滋病相关危险行为.pdf
  description: 该文件为一篇有关女女性接触者（WSW）及其与艾滋病相关危险行为的研究文献，主要探讨了女女性接触者这一特定群体中HIV传播的动态和风险因素。文中提到，WSW群体在各国都占有一定比例，且其行为特征在性健康研究中已逐渐受到重视。研究显示，该群体中大多数女性对同性性行为的认同比例并不高，且存在与异性性伴的交往情况，导致HIV感染的风险增加。文献综述了国内外关于此群体的研究，分析了不同个体性接触方式所带来的风险，以及在中国特定文化背景下的生存状况。此外，文件还探讨了该群体在医疗服务利用和艾滋病防治方面的需求，并提出了促进安全性行为的建议。
  type: document
  format: PDF Document
  size: 297308
  md5: 8c236004afa6faa1c207c3f60e2f42bd
  date: 未知
  archived: '2024-10-30 06:38:05'
  link: http://chinaepi.icdc.cn/ch/reader/download_pdf_file.aspx?journal_id=zhlxbx&file_name=A8D77C701D04C881047567B09ECCB87F12549E37C09A35937C1F0B2B2A05ADC90F707FFB2033B675B12B9020932F800E&open_type=self&file_no=20070321
  creator: ''
  tags:
  - 女女性接触者
  - 艾滋病
  - 卫生政策
  - 生存现状
  - 愈合与安全性行为教育
  - 性健康研究
  page: 女女性接触者群体及艾滋病相关危险行为_page.md
- name: 术语英文术语及背景知识存在年龄差异的关系Age-disparate
  filename: 术语英文术语及背景知识存在年龄差异的关系Age-disparate.pdf
  description: 该文件包含了一份详细的英文术语及背景知识，主要集中在与HIV/AIDS相关的术语及其定义。这些术语涵盖了与艾滋病防治、性别认同、跨性别权益及社会保障相关的重要概念，例如：年龄差异的性伴侣关系、抗逆转录病毒治疗、性别暴力、以及社会赋权等。此外，文件强调了人权在HIV应对中的重要性，并列出了包括跨性别者、同性恋者和其他重要群体在内的关键人群。文中提到：“跨性别者可能会自我认同属于跨性别者、女性、男性等身份”，突出性别认同的多样性和复杂性。
  type: document
  format: PDF Document
  size: 324519
  md5: 3f4c0d1a85e5897431fbfc81b5ca2a2d
  date: 未知
  archived: '2024-10-30 06:18:39'
  link: http://hkb980dd.pic44.websiteonline.cn/upload/15_t2mb.pdf
  creator: ''
  tags:
  - HIV
  - 艾滋病
  - 跨性别
  - 性别认同
  - 医疗资源
  - 社会保障
  - 抗病毒治疗
  - 性别暴力
  - 人权
  - 文献收集
  page: 术语英文术语及背景知识存在年龄差异的关系Age-disparate_page.md
- name: 第三册-_跨性别同盟手册A_Handbook_for_Trans_Ally
  filename: 第三册-_跨性别同盟手册A_Handbook_for_Trans_Ally.pdf
  description: 本文件是《跨性别同盟手册A Handbook for Trans Ally》的简体中文版，完整展示了跨性别及其盟友的相关知识和实践建议。本手册的内容从自序和引言开始，详尽介绍了跨性别的定义、群体及其与同志群体的关系。文件涵盖了如何成为跨性别的盟友，帮助构建更和谐的社会氛围。手册特别关注香港的跨性别法律权益与倡导历史，列出关键时间节点，如变性手术的实施和法律的变迁。此外，手册提供了应对歧视的方法、跨性别者在洗手间问题上的挑战及应对策略，以及如何在家庭、校园和工作场所建立支持性环境。文件旨在提升社会对跨性别人士的理解，消除偏见和歧视，促进平等和尊重。
  type: document
  format: PDF Document
  size: 570555
  md5: 134e0e139794cc48c7f4a1bc0f7ce6c1
  date: 未知
  archived: '2024-10-30 06:18:26'
  link: https://docs.transonline.org.cn/files/shi-fei-nan-nv-3.pdf
  creator: ''
  tags:
  - 跨性别
  - 跨性别同盟
  - 同盟手册
  - 法律权益
  - 社会环境
  - 医疗支持
  - 社会接纳
  - 性别认同
  - 抵抗歧视
  - 香港跨性别
  - 跨性别教育
  - 同志运动
  page: 第三册-_跨性别同盟手册A_Handbook_for_Trans_Ally_page.md
- name: 艾滋病与跨性别者及其它多元性别群体
  filename: 艾滋病与跨性别者及其它多元性别群体.pdf
  description: 本文件探讨了艾滋病与跨性别者及其他多元性别群体之间的关系，重点关注这一群体在健康护理中的特殊需求与挑战。尽管文件内容为空，但可以推测，可能涵盖艾滋病的传播特征、预防措施，以及跨性别者在接受医疗服务时所面临的歧视和障碍。此外，可能会讨论如何为跨性别者和多元性别群体提供更好的支持与资源，包括心理健康服务和权利保障。此文档旨在提高公众对跨性别者健康问题的认识，并倡导社会对这一群体的理解与包容。
  type: document
  format: PDF Document
  size: 6929508
  md5: 589dad07fd7199a4895069d50b7fc67d
  date: 未知
  archived: '2024-10-30 06:36:34'
  link: http://hkb980dd.pic44.websiteonline.cn/upload/16gh.pdf
  creator: ''
  tags:
  - 艾滋病
  - 跨性别者
  - 健康护理
  - 医疗资源
  - 社会支持
  - 多元性别
  page: 艾滋病与跨性别者及其它多元性别群体_page.md
- name: 艾滋病防治社会组织大有作为
  filename: 艾滋病防治社会组织大有作为.pdf
  description: 该文件名为《艾滋病防治社会组织大有作为》，由许锐恒撰写，发布时间为2014年11月。文件主要探讨了社会组织在艾滋病防治中的重要作用及其贡献，特别关注高危人群和跨性别人群的状况。当中提到，性传播是HIV的主要传播途径，报告中的数据涉及到2011年中国艾滋病感染者的具体情况，包括性别、传播方式及新发感染的比率。此外，文中还跟踪了2013年中国艾滋病防治活动的进展，并提到了“世界艾滋病日”的主题，强调需要动员各方力量参与防治工作。通过数据说明重点人群的艾滋病流行情况，以及社会对艾滋病患者的歧视和社会组织在此中的作用。
  type: document
  format: PDF Document
  size: 4422301
  md5: 53650c3d14af253ba1911a3d0956130f
  date: 2014-11
  archived: '2024-10-30 06:18:02'
  link: http://cdcp.gd.gov.cn/attachment/0/495/495039/3442088.pdf
  creator: ''
  tags:
  - 艾滋病
  - HIV
  - 社会组织
  - 跨性别
  - 防治
  - 法律政策
  - 数据统计
  - 健康护理
  - 性传播
  - 高危人群
  page: 艾滋病防治社会组织大有作为_page.md
- name: 跨性别和多元性别人群健康照护指南（第八版)
  filename: 跨性别和多元性别人群健康照护指南（第八版).pdf
  description: 该文件为《跨性别和多元性别人群健康照护指南（第八版）》的中文翻译版。这本指南由众多跨性别健康领域的专家共同撰写，旨在为跨性别及性别多样性人群提供全面的健康护理标准。文件中详细探讨了跨性别及性别多样性人群面临的特殊健康问题，包括心理健康、内分泌、外科手术、性传播感染预防、以及基本健康保健服务等内容。此外，该指南还强调了尊重和支持的医疗环境的重要性，以帮助跨性别个体实现更好的健康照护。该指南的更新版也考虑了不同地区的医疗、社会和法律环境，导致跨性别者所接受的护理和服务可能会有所不同。在文末提供了多位区域内专家的联系方式，供跨性别者和医疗提供者进一步咨询和交流。
  type: document
  format: PDF Document
  size: 3738717
  md5: 168fc7b79987574bdd192280702eaa32
  date: '2022-09-15'
  archived: '2024-10-30 07:09:04'
  link: https://docs-cdn.transonline.org.cn/files/SOC-V8-CN.pdf
  creator: ''
  tags:
  - 跨性别健康
  - 医疗指南
  - 性别多样性
  - 健康照护标准
  - 心理健康
  - 性别认同
  - 跨性别权利
  page: 跨性别和多元性别人群健康照护指南（第八版)_page.md
- name: 跨性别女性_3_未治疗或治疗后未达到病毒抑制的_感染者
  filename: 跨性别女性_3_未治疗或治疗后未达到病毒抑制的_感染者.pdf
  description: 该文档探讨了跨性别女性在医疗领域中所面临的治疗和健康问题，尤其是未治疗或治疗后未达到病毒抑制的感染者。文件内容可能包括相关的医疗案例研究、经历分享和影响健康的因素评估等，旨在提高对跨性别女性在健康护理中面临挑战的认识。文中可能讨论了在治疗过程中，跨性别女性如何应对医疗系统的障碍，以及她们的健康权益和需求。
  type: document
  format: PDF Document
  size: 3721053
  md5: ac091396ff32e28f09fb13f8a8568df3
  date: 未知
  archived: '2024-10-30 06:41:49'
  link: http://www.qidong.gov.cn/qdswjw/upload/22492ed5-e70d-4395-be84-da6395bfd014.pdf
  creator: ''
  tags:
  - 跨性别女性
  - 健康护理
  - 病毒抑制
  - 医疗资源
  - 案例研究
  page: 跨性别女性_3_未治疗或治疗后未达到病毒抑制的_感染者_page.md
- name: 跨性别女性的特征及艾滋病相关知识行为调查
  filename: 跨性别女性的特征及艾滋病相关知识行为调查.pdf
  description: 本文件为关于跨性别女性特征及其与艾滋病相关知识行为的调查研究。文件内容包括调查的背景、方法、样本选择及其结果分析，旨在揭示跨性别女性在艾滋病相关知识和行为方面的现状。通过对样本的调查，研究所发现的行为模式与社会环境为理解这一群体的生存挑战提供了重要视角和数据支持。该研究强调了提高跨性别女性群体的健康知识和社会支持的重要性，以帮助改善其生存状况和健康结果。
  type: document
  format: PDF Document
  size: 1661522
  md5: 09b0119954a07fe18adc7f4b95f12fc3
  date: 未知
  archived: '2024-10-30 07:09:18'
  link: http://chinaepi.icdc.cn/ch/reader/download_pdf_file.aspx?journal_id=zhlxbx&file_name=8101D5DAB1C08948E75602FF36EC0DAE997B349F20780245349618035C29863401CC68A39FF5E763DD5ABCA5C3495EC981BFAEEA5D0BD8C0D4B94448DB18C3C0&open_type=self&file_no=20160116
  creator: ''
  tags:
  - 跨性别女性
  - 艾滋病
  - 健康知识
  - 调查研究
  - 社会支持
  page: 跨性别女性的特征及艾滋病相关知识行为调查_page.md
- name: 青少年性教育是什么
  filename: 青少年性教育是什么.pdf
  description: 该文件名为《青少年性教育是什么》，发表于《中华人类性科学》2011年第20卷第2期，主要探讨青少年性教育的重要性和方针。文章强调青少年在青春期需要接受关于性的知识教育，并提出针对不同问题的性教育策略，如青春期教育、艾滋病预防教育、生活技能教育等。此外，文章指出全面的性教育应涵盖生理、心理、法律以及伦理道德等方面的知识，以帮助青少年形成积极的性观念，提高他们在面对性相关问题时的应对能力。文章中提到，性不仅是生物学的现象，还包括心理学和社会学的意义，应当从多个层面进行教育。
  type: document
  format: PDF Document
  size: 2069011
  md5: 5ebd8ee9a5b04bef73460bcb019b0b6d
  date: '2011-02-01'
  archived: '2024-10-30 06:40:06'
  link: http://www.zgxkxzzs.com/uploadfile/zgxkx/20180419/%E4%B8%AD%E5%9B%BD%E6%80%A7%E7%A7%91%E5%AD%A611-2.pdf
  creator: ''
  tags:
  - 青少年性教育
  - 性知识
  - 性权利教育
  - 心理健康
  - 性别平等教育
  - 中华人类性科学
  page: 青少年性教育是什么_page.md
subdirs: []
