name: 社科论文与期刊
description: 本目录收录了与跨性别相关的社科论文与期刊，涉及性别伦理、婚姻家庭、社会行为等领域的讨论与研究，提供了对跨性别者经历和现状的深刻分析与见解。
curator: ''
source: ''
tags:
- 社科论文
- 性别伦理
- 婚姻与家庭
- 跨性别研究
- 社会行为
- 文化交流
- 性别平等
- 自杀意念
- 运动员
- 酷儿理论
license: ''
files:
- name: 个人化的婚姻和家庭
  filename: 个人化的婚姻和家庭.pdf
  description: 本文件为刘巍撰写的社科论文《个人化的婚姻和家庭》，发表在《法國研究（Etudes Françaises）》2015年第4期。文章详细探讨了当代法国婚姻与家庭的显著变化，着重分析了家庭结构的多样化和个性化趋势。文中指出，婚姻作为社会的基本单位，经历了深刻的演变，从以家族利益为主的传统模式向以个人选择和情感为基础的现代婚姻转变。文章提到，法国在法律上于2013年允许同性婚姻，标志着社会对于婚姻观念的开放与多元化。该文通过家庭结构、婚姻形式的变化以及法国社会对未婚同居和同性婚姻的接受度反映了当代社会的演变。
  type: document
  format: PDF Document
  size: 1430500
  md5: 312256eead31c8b980fb507dceac1bf1
  date: '2015-12-30'
  archived: '2024-10-30 06:44:57'
  link: https://jxpt.whut.edu.cn/meol/analytics/resPdfShow.do;jsessionid=0BB9C7D091040A20215CE9C31AA34E33?resId=163387&lid=9179
  creator: ''
  tags:
  - 个人化
  - 婚姻
  - 家庭
  - 社会变迁
  - 法国
  - 同性婚姻
  - 未婚同居
  - 社科论文
  - 法律政策
  page: 个人化的婚姻和家庭_page.md
- name: 人工智能与性别伦理一个新时代
  filename: 人工智能与性别伦理一个新时代.pdf
  description: 本文件为马中红的社科论文，探讨了人工智能与性别伦理之间的关系。文章指出，传统的性别伦理是建立在男性与女性二元二分的体系上，但随着人工智能时代的到来，这一体系受到冲击。文件中具体分析了科技与社会、文化之间的互动，以及如何面对新技术带来的性别伦理挑战。作者提到，例如人工智能助手和伴侣机器人往往使用女性形象，这在某种程度上加强了并固化了传统性别角色。此外，文件还探讨了如何建立新的性别平等伦理、多元和差异互补性别伦理，以及人造物与人类之间应有的伦理关系。
  type: document
  format: PDF Document
  size: 1400966
  md5: 41da5e7075f016f9c35792bbdc439eb8
  date: 未知
  archived: '2024-10-30 06:41:02'
  link: http://www.pkujccs.cn/uploads/attachments/20200708/73ce1982e7a9fe5dbcb87dccb6e410ad.pdf
  creator: ''
  tags:
  - 人工智能
  - 性别伦理
  - 科技女性主义
  - 传统性别观念
  - 跨性别
  - 数字文化
  - 性别平等
  - 社会性别
  - 机器伦理
  page: 人工智能与性别伦理一个新时代_page.md
- name: 人工智能时代性别伦理的多维思考与前瞻性治理
  filename: 人工智能时代性别伦理的多维思考与前瞻性治理.pdf
  description: 本文探讨了在人工智能时代性别伦理的复杂性和多维性，分析了人工智能技术如何映射和放大现有性别问题的两个维度：一是技术逻辑使得性别偏见通过算法得以客观化，二是技术从业者的性别单一性在技术开发中的伦理观念的嵌入。文章指出，“第三性”的人造智能生命体出现可能打破传统的两性二元对立，提出人机之间的新性别伦理关系。最后，作者呼吁社会治理者要对人工智能的技术发展进行前瞻性治理，以构建适应现代社会的性别伦理观念。
  type: document
  format: PDF Document
  size: 675578
  md5: 15f98bc7da61799ae6b8387be0999ce2
  date: '2022-07-01'
  archived: '2024-10-30 06:40:55'
  link: http://www.szass.com/attachment/0/52/52065/826459.pdf
  creator: ''
  tags:
  - 人工智能
  - 性别伦理
  - 政府治理
  - 社会公正
  - 性别偏见
  - 跨性别
  - 技术伦理
  - 性别差异
  - 人工智能技术
  page: 人工智能时代性别伦理的多维思考与前瞻性治理_page.md
- name: 人类社会行为的双重属性及其双重判断
  filename: 人类社会行为的双重属性及其双重判断.pdf
  description: 该文件为2022年发布的社科论文，讨论了人类社会行为的双重属性及其双重判断。作者吴家睿在文中探讨了生物学因素与文化环境如何共同影响人类的社会行为，特别是在同性性行为与跨性别议题上，强调了从遗传学角度对人类行为的影响，以及文化属性在社会结构中所扮演的重要角色。文章引用了大量研究数据，说明人类行为并非单纯由遗传决定，而是受社会环境与文化背景的深刻影响，同时也探讨了科学判断与价值判断在社会行为讨论中的互动和冲突。例如，指出了基因在性取向中的有限作用以及社会接纳度变化对现代人群体的影响。通过对多个案例的分析，作者强调文化的快速演进对社会行为的塑造作用。
  type: document
  format: PDF Document
  size: 377874
  md5: 256edf1a252177de6faee6b0df47a3c3
  date: 2022年7月
  archived: '2024-10-30 06:26:05'
  link: https://lifescience.sinh.ac.cn/webadmin/upload/20221206151607_3451_8129.pdf
  creator: ''
  tags:
  - 社会行为
  - 跨性别
  - 生物学与文化
  - 遗传学
  - ' LGBTQ'
  - 科学判断
  - 价值判断
  - 同性性行为
  - 人类行为研究
  page: 人类社会行为的双重属性及其双重判断_page.md
- name: 从后学到认同政治_当代美国人文思潮走向
  filename: 从后学到认同政治_当代美国人文思潮走向.pdf
  description: 本文探讨了后学与认同政治在美国人文学术中的发展，着重分析了在后结构主义、后现代主义及后殖民主义背景下，认同政治如何从文化理论演变为现实政治的关键概念。作者刘康回顾了20世纪以来，尤其是1960至1970年代的文化革命中，如何在美国学术界形成激进的左翼思潮与认同政治的主流。文章进一步探讨了马克思、尼采和弗洛伊德等思想家的理论对认同政治的影响，以及这些理论如何被后续的学者，包括萨义德和詹姆逊等，融合、修正并在后续的文化运动中重新定义。总的来说，本文揭示了认同政治与美国多元文化及其社会运动的复杂关系，以及这种关系如何反映在当今的政治语境中。
  type: document
  format: PDF Document
  size: 1055136
  md5: 935a4ae7d0fbc5b10b4100ca28608f5a
  date: 未知
  archived: '2024-11-01 19:02:18'
  link: https://www.xsyk021.com/fileXSYK/journal/article/xsyk/2020/2/PDF/liukang.pdf
  creator: ''
  tags:
  - 后学
  - 认同政治
  - 美国人文学术
  - 文化革命
  - 后结构主义
  - 后现代主义
  - 后殖民主义
  - 刘康
  - 文化多元
  - 历史演变
  page: 从后学到认同政治_当代美国人文思潮走向_page.md
- name: 从２０１９年纽约左翼论坛看西方左翼思想发展动态
  filename: 从２０１９年纽约左翼论坛看西方左翼思想发展动态.pdf
  description: 本文分析了2019年纽约左翼论坛讨论西方左翼思想发展的动态，具体聚焦于当前全球经济、社会政治危机背景下，特朗普主义对多元弱势群体（包括LGBTQ群体）的威胁与反思。作者田曦指出，左翼论坛探讨了如何在崛起的法西斯主义和新帝国主义背景中，推动社会正义，保护弱势群体的权益。文件中提到会议设置了多个专题，以探讨如何应对特朗普政府带来的危机，参会者对种族主义、性别压迫、以及资本主义批判的不同视角进行了深入的辩论。
  type: document
  format: PDF Document
  size: 1232563
  md5: 5d7a36b33beea3662a756503a5381986
  date: '2019'
  archived: '2024-10-30 06:47:16'
  link: https://mkszyyj.ajcass.com/UploadFile/Issue/lhotypk2.pdf
  creator: ''
  tags:
  - 纽约左翼论坛
  - 特朗普主义
  - 资本主义
  - LGBTQ权益
  - 社会正义
  - 性别压迫
  - 全球经济危机
  page: 从２０１９年纽约左翼论坛看西方左翼思想发展动态_page.md
- name: 何谓跨文化_自我与他者的吊诡共生
  filename: 何谓跨文化_自我与他者的吊诡共生.pdf
  description: 该文件标题为《何谓跨文化_自我与他者的吊诡共生》，由台湾“中研院”中国文哲研究所的研究员彭小妍撰写。内容主要探讨了跨文化研究这一新兴的研究范式，及其与传统比较研究、文化研究和后殖民研究的不同之处。彭小妍指出，跨文化研究强调自我与他者之间的接触交融，并试图打破二元划分的思维方式，主张主体的流动性以及文化的混杂性。该文分析了全球化背景下文化身份认同的复杂性，并从历史与现代的结合角度，探讨了在不同文化间交流中“自我”与“他者”的动态关系。
  type: document
  format: PDF Document
  size: 691090
  md5: 4a0d56f1623c36549d3ca89d635dc0bc
  date: 未知
  archived: '2024-11-01 09:18:22'
  link: https://www.tsyzm.com/fileup/1004-2229/NEWS/20220720105228.pdf
  creator: ''
  tags:
  - 跨文化研究
  - 自我与他者
  - 全球化
  - 身份认同
  - 文化混杂
  - 社会变迁
  - 比较研究
  - 后殖民研究
  page: 何谓跨文化_自我与他者的吊诡共生_page.md
- name: 变性手术算病假_整容手术算病假吗
  filename: 变性手术算病假_整容手术算病假吗.pdf
  description: 此文件分析了变性手术和整容手术在病假认定上的法律争议。内容中提到了一则案例，讨论了一名因进行双眼皮手术而被公司辞退的员工谭某，法院未支持其病假申请。文章通过引用法律条款，探讨了男性转女性变性手术和整容手术在劳动法中的不同性质。作者指出，病假应以劳动者是否有疾病为标准，而变性手术对于部分人来说是必要的医疗行为，而整容则与美观相关，没有同等的医学必要性。最终，文章呼吁社会要包容和尊重跨性别者的身份及其公民权利，提倡社会对于多元化生存方式的理解和包容。
  type: document
  format: PDF Document
  size: 316588
  md5: 3e3d6fe2c9a5dfe23757539272240c57
  date: '2020-07-08'
  archived: '2024-10-30 06:26:05'
  link: http://epaper.file.routeryun.com/ldb/other/5f04b9994b592.pdf
  creator: ''
  tags:
  - 变性手术
  - 病假
  - 整容手术
  - 法律问题
  - 社会包容
  - 跨性别权利
  page: 变性手术算病假_整容手术算病假吗_page.md
- name: 对同性恋和性取向异源性的跨学科观
  filename: 对同性恋和性取向异源性的跨学科观.pdf
  description: 本文为对同性恋和性取向异源性的跨学科观察，讨论了同性性行为的多种成因，包括内源性和外源性因素。研究者沈政详细分析了同性恋及其性取向的形成过程，提出了内外源性因素对其影响的科学依据。文章指出，发展性同性性行为主要受生物学因素影响，如基因、激素、脑的性别分化等，而获得性同性性行为则更多受到社会环境、家庭状况等外部因素的影响。文中引用了大量文献和实证研究，探讨了当前关于性少数群体的研究现状与未来方向。
  type: document
  format: PDF Document
  size: 579146
  md5: 5ca16d15dd47b2d4d099edac590e6bf2
  date: '2015-03-31'
  archived: '2024-10-30 07:09:07'
  link: https://dds.sciengine.com/cfs/files/pdfs/0023-074X/7uNZpW3qqJa3xkhcx-mark.pdf
  creator: ''
  tags:
  - 同性恋
  - 性取向
  - 跨学科研究
  - 发育性同性性行为
  - 获得性同性性行为
  - 社会影响
  - 医学证据
  page: 对同性恋和性取向异源性的跨学科观_page.md
- name: 小号中的叙事认同与爵士乐身份
  filename: 小号中的叙事认同与爵士乐身份.pdf
  description: 本文探讨了杰琪·凯的小说《小号》中主人公乔斯·穆迪的身份构建，特别是他作为多种族和跨性别爵士音乐家的复杂性。文章从叙事认同的视角分析，指出穆迪的女性身体与男性身份形成公众关注的焦点，特别是传记家斯通斯对其身份的商业化解读对穆迪家庭所造成的困扰。穆迪通过爵士乐的即兴特性构建了流动性身份，反映了编织多元文化与个人身份之间的张力。最后，穆迪的养子科尔曼在面对父亲身份的危机之际，通过接受穆迪的身份及其遗传谱系，找到了重建自我和家庭的希望。
  type: document
  format: PDF Document
  size: 1592031
  md5: 3789deefe8db4bff01cde81d58897e45
  date: 2020-09
  archived: '2024-10-30 06:35:28'
  link: https://skxb.hnust.edu.cn/hnkjdxxbsk/article/pdf/202005007?file_name=55455A4859C3AA36F4A4D355050451DBBEA0D2D07942409325CF498C9B33998D106E9881BC1DF74EC58D2947CA52C30D3D763C2EB53544AF70297F14E2C99E18&open_type=self
  creator: ''
  tags:
  - 跨性别
  - 爵士乐
  - 身份构建
  - 多种族
  - 叙事认同
  - 杰琪·凯
  - 文学分析
  - 生命故事
  page: 小号中的叙事认同与爵士乐身份_page.md
- name: 性行为和性规范多样性研讨会的内容探讨
  filename: 性行为和性规范多样性研讨会的内容探讨.pdf
  description: 该文件为一篇关于性行为与性规范多样性的社科论文，其中包含了在某次研讨会上对该主题的探讨内容。尽管未能提取具体文本，但可以推测该研讨会涉及跨性别者在性行为和性规范方面面临的多样性挑战与讨论，可能涵盖跨性别群体的生活经历、社会认同与相关的法律法规。文章或许还会提供一系列观点及案例分析，促进对跨性别和性多样性问题的理解与思考。
  type: document
  format: PDF Document
  size: 146
  md5: 8eec510e57f5f732fd2cce73df7b73ef
  date: 未知
  archived: '2024-11-01 09:18:45'
  link: https://www.mzywfyj.org.cn/downloadRepository/9ab0c665-653b-4ae5-b081-8d4b76f01239.pdf
  creator: ''
  tags:
  - 跨性别
  - 性行为
  - 性规范
  - 社会科学
  - 研讨会
  - 政策研究
  page: 性行为和性规范多样性研讨会的内容探讨_page.md
- name: 新探索与内卷化_2015-2017年西方跨文化传播研究述评
  filename: 新探索与内卷化_2015-2017年西方跨文化传播研究述评.pdf
  description: 这篇文章是对2015至2017年期间西方跨文化传播研究领域546篇英文文献的述评，分析了跨文化传播的拓展和内卷化现象。文章讨论了移民、难民与性别权益等多重身份问题，以及文化适应理论的细化和固化现象。作者指出，尽管西方学者努力吸纳非西方元素，但西方化思维依然支配着研究者，对跨文化传播现状的反思需要继续深入。此外，文章还提到了互联网时代对跨文化交流的影响，例如网络的多样性与限制，展示了这一领域的研究进展和盲区。
  type: document
  format: PDF Document
  size: 1069846
  md5: ecccd236077013d9a217a3f35a4f38f7
  date: 2018-04
  archived: '2024-10-30 06:40:46'
  link: http://journal.whu.edu.cn/uploadfiles/jcr2018no1/201804176hla3_6833.pdf
  creator: ''
  tags:
  - 跨文化传播
  - 研究述评
  - 移民问题
  - 难民危机
  - 性别权益
  - 文化适应理论
  - 西方化思维
  - 互联网影响
  - 身份认同
  page: 新探索与内卷化_2015-2017年西方跨文化传播研究述评_page.md
- name: 流行歌曲中意象符号的性别使用差异
  filename: 流行歌曲中意象符号的性别使用差异.pdf
  description: 本文探讨了流行歌曲中的性别意象及其使用差异，揭示了流行歌曲在性别文化建构中的复杂作用。作者陆正兰重点分析了男歌和女歌在歌词意象选择上的不同，指出这种差异不仅反映了性别意识的深刻影响，还在当代文化中扮演着特殊角色。文章中提到，流行歌曲因其大众化性质，其性别表达往往会被忽视，然而，实际上男歌多侧重于歌颂女性的外表，而女歌则更关注男性的精神品质。本文通过具体歌曲的例子，如《我愿意》、《月亮代表我的心》等，详细阐述了性别意象在流行歌曲中的普遍性及其文化内涵。
  type: document
  format: PDF Document
  size: 1170906
  md5: 0816243be7f0d66e5cb90f9285c308d5
  date: 未知
  archived: '2024-10-30 06:39:20'
  link: http://www.semiotics.net.cn/userfiles/images/76f3e533255d6cb11f227bde1046aa52.pdf
  creator: ''
  tags:
  - 流行歌曲
  - 性别意象
  - 文化研究
  - 性别差异
  - 歌词分析
  - 社会文化
  - 音乐与性别
  page: 流行歌曲中意象符号的性别使用差异_page.md
- name: 男男性服务群体的性_性网络艾滋风险
  filename: 男男性服务群体的性_性网络艾滋风险.pdf
  description: 该文件为一篇关于男男性服务群体的社会科学研究论文，探讨了东北地区男男性服务者的性、性网络及艾滋病毒感染风险。文章通过参与观察、个案深入访谈与小组讨论等定性研究方法，分析了男男性服务者的多元化生存状态、文化特点和艾滋病防治的社会科学建议。研究显示，男男性服务者不仅面临着法律和社会环境的双重压力，还在性身份认同和经济利益之间进行艰难的平衡。此外，文件中详细记录了男男性服务者在娱乐场所、家庭式会所和公共空间中的活动特征，以及这些场所的管理模式和客群构成。文中还提到男男性干预策略的不足，强调了社会科学视角的重要性。
  type: document
  format: PDF Document
  size: 156304
  md5: e1e75201421f541ce8cf7f78608dd884
  date: '2012-07-01'
  archived: '2024-10-30 06:36:44'
  link: https://rkyj.ruc.edu.cn/EN/article/downloadArticleFile.do?attachType=PDF&id=36
  creator: ''
  tags:
  - 男男性服务者
  - 艾滋病毒风险
  - 社会研究
  - 性服务网络
  - 东北地区
  - 性身份认同
  - 艾滋病防治
  - 文化研究
  - 医疗资源
  page: 男男性服务群体的性_性网络艾滋风险_page.md
- name: 社会语言学视阈下的英语性别语言差异研究
  filename: 社会语言学视阈下的英语性别语言差异研究.pdf
  description: 该文献为2015年发表的社会科学论文，作者吴栋梁，研究了社会语言学视阈下的英语性别语言差异。文章探讨了语言与性别之间的关系，分析了男性与女性在语调、语义、句法、话语量及话题应答等方面的差异，指出这些差异受社会分工、地位和心理的影响，反映出性别角色的社会期待和语言偏见。文中提到，尽管近年来女权主义兴起，社会观念有所改变，但男性在语言表达中仍占主导地位。
  type: document
  format: PDF Document
  size: 1801966
  md5: 063e8ec72a1d9a66b62e4c7d346fcf1f
  date: '2015-03-01'
  archived: '2024-11-01 09:20:22'
  link: https://xbsk.xcc.edu.cn/xcxyxbsk/article/pdf/201501042?file_name=88D0BB702E5C17073B328E5E10ED951A6A7533E02340340AD7139CC808F3CEB6A9BDD17E0EC35B991C2B448B58ACD52BED6315804559D005112AC9DAA119B53D&open_type=self
  creator: ''
  tags:
  - 社会语言学
  - 性别差异
  - 英语语言
  - 跨性别交流
  - 语言与性别
  - 社会心理学
  - 语言研究
  - 性别角色
  - 男女性别差异
  page: 社会语言学视阈下的英语性别语言差异研究_page.md
- name: 竞技人文传播东京2020_奥运会系列事件的思考
  filename: 竞技人文传播东京2020_奥运会系列事件的思考.pdf
  description: 本文件是关于2020年东京奥运会的社科论文，刊载于《成都体育学院学报》。文章从竞技、人文和传播的角度对东京奥运会进行深入分析。作者探讨了奥运会在现代文明社会中的权力、话语、游戏精神与身份表征，指出该赛事反映了中国竞技体育的现状及未来改革方向。论文涉及多个热点议题，包括中国体育代表团的表现、性别平等、奥林匹克格言的变化，以及国际媒体对中国表现的刻意淡化等。文章强调意识形态对体育形象的影响，表明东京奥运会是探讨性别平等与文化传播的重要时刻，还讨论了变性人参与奥运的问题和媒体在其中的角色。
  type: document
  format: PDF Document
  size: 1411992
  md5: e0341e0a506c618a2e6e449c4f6e6a94
  date: '2021-06-30'
  archived: '2024-10-30 06:26:05'
  link: http://cdtyxb.cdsu.edu.cn/CN/article/downloadArticleFile.do?attachType=PDF&id=1316
  creator: ''
  tags:
  - 东京奥运会
  - 性别平等
  - 文化传播
  - 竞技体育
  - 社科研究
  - 媒体形象
  - 变性人参与
  - 女性运动员
  - 奥林匹克精神
  - 国际舆论
  page: 竞技人文传播东京2020_奥运会系列事件的思考_page.md
- name: 美国反种族歧视的黑命亦命运动探析
  filename: 美国反种族歧视的黑命亦命运动探析.pdf
  description: 该文件为一篇探讨美国反种族歧视的#黑命亦命$运动的社科论文，详细分析了这一运动的起源、发展、观念和政策主张。文章指出，黑命亦命运动通过社交媒体的力量引起了全球关注，重点关注反对系统性种族歧视的问题，特别是在刑事司法领域内对黑人生命权的侵犯。这项运动激起了广泛的社会讨论，并与女权主义、国际主义及其他少数族群的解放运动相结合。论文还探讨了运动的组织结构、参与主体的多元化，以及反种族主义的核心观念，并提出了一系列政策主张，如废除警察暴力、改善黑人经济和教育状况等。
  type: document
  format: PDF Document
  size: 1105053
  md5: 4e9391b37d5d22b8bd6ab762c753a254
  date: 未知
  archived: '2024-10-30 06:26:06'
  link: https://mzyj.ajcass.com/Admin/UploadFile/Issue/201707310001/2021/12//20211229095617WU_FILE_0.pdf
  creator: ''
  tags:
  - 黑命亦命
  - 反种族歧视
  - 社交媒体运动
  - 政策主张
  - 美国政治文化
  - 多元化
  - 刑事司法
  - 种族平等
  page: 美国反种族歧视的黑命亦命运动探析_page.md
- name: 西方大学生身份研究及其启示
  filename: 西方大学生身份研究及其启示.pdf
  description: 该文档是关于西方大学生身份研究的论文，发表于《高等教育研究学报》第37卷第2期，主要探讨大学生身份的心理学、社会学和社会心理学等多学科视角。文章总结了过去60年间对大学生身份的研究成果，强调这些研究对于大学生、大学管理人员和教育工作者的重要意义。作者粟进英与龚双萍通过对心理发展理论、社会环境影响及个体归属感等方面的深入分析，指出大学生身份的发展过程与社会文化背景的紧密联系，并提出新兴身份研究方法的启示。文件中涉及的关键词包括：大学生、身份、研究。
  type: document
  format: PDF Document
  size: 290903
  md5: eb707033e66a9477d1ad7e09891b372f
  date: 2014年6月
  archived: '2024-10-30 06:41:39'
  link: http://gdjyyjxb.nudt.edu.cn/ch/reader/create_pdf.aspx?file_no=20140216&year_id=2014&quarter_id=2&falg=1
  creator: ''
  tags:
  - 大学生身份
  - 心理学研究
  - 社会学研究
  - 社会心理学
  - 教育
  - 西方研究
  - 身份发展
  - 高等教育
  page: 西方大学生身份研究及其启示_page.md
- name: 西方的变性热_王克强
  filename: 西方的变性热_王克强.pdf
  description: 本文件为王克强撰写的社科论文，探讨了西方社会中跨性别群体的变性现象及其所面临的文化、法律和社会挑战。文章通过对变性热的历史演变和社会接受度进行分析，指出跨性别个体在寻求社会认同与医疗支持方面的困境，以及西方各国在法律政策上对于跨性别者权利的不同态度。王克强还引用了多项数据和案例，展示了不同文化背景下跨性别者的生存状态及心理需求，为理解跨性别问题提供了丰富的视角，力求引发更广泛的社会讨论。
  type: document
  format: PDF Document
  size: 73066
  md5: 3366131a1785efee8612229e92aec724
  date: 未知
  archived: '2024-10-30 15:46:37'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 变性
  - 社会学
  - 法律政策
  - 西方文化
  - 心理健康
  page: 西方的变性热_王克强_page.md
- name: 论社会性别理论视域下的女性研究及其争论
  filename: 论社会性别理论视域下的女性研究及其争论.pdf
  description: 该文档探讨了社会性别理论对女性研究的影响以及相关争论。文章从社会性别理论的起源谈起，指出其在20世纪70年代随着罗伯特·斯托勒的研究而兴起，强调社会对男女身份认同的塑造及其导致的性别气质差异与等级结构。同时，文中批判了社会性别理论的局限性，指出其导致的关注狭隘化和对权力一般化的倾向。在讨论女性研究的发展时，作者认为，社会性别理论的推广为女性研究提供了更加开放的视野，虽然强调生物性别与社会性别的界限，但也面临被误判和约束的问题。文章中提到：“生物性别和社会性别并不是任意关联的”，并探讨了不同文化和社会中性别角色定位的问题。
  type: document
  format: PDF Document
  size: 1284201
  md5: ea699563e802afd0bb743f1c91e36bd5
  date: 未知
  archived: '2024-10-30 06:39:01'
  link: https://tsla.ecnu.edu.cn/CN/article/downloadArticleFile.do?attachType=PDF&id=702
  creator: ''
  tags:
  - 社会性别理论
  - 女性研究
  - 权力结构
  - 性别气质
  - 文化研究
  - 生物性别与社会性别的关系
  - 女权主义
  page: 论社会性别理论视域下的女性研究及其争论_page.md
- name: 话语竞争与性别平等理念的传播
  filename: 话语竞争与性别平等理念的传播.pdf
  description: 该文献探讨了在传统与新兴媒体中性别形象的传播与竞争。作者从媒体的角色出发，分析了男女平等作为国家基本国策在社会传播中的现状与局限性。文中提到，尽管社会对于性别平等意识的认同逐渐加深，媒介内容的管理与监管依然存在不足，亟需进一步推动性别主流化。作者提到，随着新媒体的崛起，性别平等的理念传递面临新的挑战与机遇，尤其是在年轻群体中参与创造和传播性别平等的知识。文章还讨论了新型性别概念如“女汉子”和“暖男”的涌现对传统性别角色的冲击，以及如何在消费时代挑战传统性别刻板印象。最终，作者呼吁重视性别话语的创新与传播，以建设一个更包容的性别平等环境。
  type: document
  format: PDF Document
  size: 119922
  md5: c008d7f3a4c5a7ad7cd4b6c5fd59ba13
  date: 未知
  archived: '2024-10-30 06:39:11'
  link: http://www.shehui.pku.edu.cn/upload/editor/file/20181026/20181026093824_7629.pdf
  creator: ''
  tags:
  - 性别平等
  - 媒体传播
  - 性别角色
  - 新媒体
  - 社会文化
  - 性别意识
  - 男权文化
  - 消费社会
  page: 话语竞争与性别平等理念的传播_page.md
- name: 跨性别女性人群心理特征及相关行为分析
  filename: 跨性别女性人群心理特征及相关行为分析.pdf
  description: 该文档为一篇关于跨性别女性人群心理特征及相关行为分析的社科论文，发表于2018年12月的《中国公共卫生》杂志。研究通过滚雪球抽样方法在山东省进行，为期近两年的调研，调查对象多为20到40岁之间的跨性别女性。文中详细描述了被调查者的心理特征、行为表现以及面临的健康风险，特别是艾滋病感染的风险。研究结果显示，51.2%的受访者认同自己为完全女性心理性别，而48.8%的人心理性别则表现模糊，且两组在婚姻状态、工作稳定性、性行为等各项指标上存在显著差异。该研究为针对跨性别女性的医疗和社会支持提供了重要数据和建议。
  type: document
  format: PDF Document
  size: 489744
  md5: 576374d96e4e04b3028afc7739f3d29b
  date: '2018-11-01'
  archived: '2024-11-01 09:20:08'
  link: https://www.zgggws.com/cn/article/pdf/preview/10.11847/zgggws1118684.pdf
  creator: ''
  tags:
  - 跨性别女性
  - 心理特征
  - 行为分析
  - 艾滋病风险
  - 社会调查
  - 山东省调研
  page: 跨性别女性人群心理特征及相关行为分析_page.md
- name: 跨性别者自杀意念的影响因素探析Analysis_of_Influencing_Factors_of
  filename: 跨性别者自杀意念的影响因素探析Analysis_of_Influencing_Factors_of.pdf
  description: 本文件为李记勇撰写的社科论文，题目为《跨性别者自杀意念的影响因素探析》。论文中探讨了跨性别者作为社会边缘群体所面临的心理压力及其自杀意念的高发原因。研究指出，跨性别者由于性别不一致所带来的社会期待和歧视，导致其心理健康问题频发，抑郁和焦虑水平上升。该文通过对多项研究的归纳，分析了歧视、性暴力、家庭支持、社会接纳和个体应对策略等因素对跨性别者自杀意念的影响。尤其强调家庭和社会支持对降低自我伤害风险的重要性，且指出现阶段对跨性别者的研究仍显不足。
  type: document
  format: PDF Document
  size: 450280
  md5: fcffc14dba958bcba3e0d7c880a0e8c3
  date: 2023年1月29日
  archived: '2024-10-30 06:37:59'
  link: https://pdf.hanspub.org/ASS20230100000_55689888.pdf
  creator: ''
  tags:
  - 跨性别者
  - 自杀意念
  - 心理健康
  - 社会支持
  - 歧视
  - 性暴力
  - 家庭支持
  - 社会接纳
  page: 跨性别者自杀意念的影响因素探析Analysis_of_Influencing_Factors_of_page.md
- name: 跨性别运动员参加高水平体育比赛的科学思考
  filename: 跨性别运动员参加高水平体育比赛的科学思考.pdf
  description: 本文件标题为《跨性别运动员参加高水平体育比赛的科学思考》，由田野教授撰写，发表于2021年。这篇论文讨论了跨性别运动员在女子高水平体育比赛中的参与，分析了与之相关的科学、伦理和社会学问题。文中提到，新西兰变性运动员劳拉·哈伯德在2020年东京奥运会成为全球首位由男性变为女性参加女子比赛的运动员，引发广泛关注与争议。文章回顾了跨性别运动员参加女子比赛的重要事件，探讨了运动员的性别检测历史，讨论了在运动员身份认同与公平竞争之间的复杂关系。文件中引用了多种历史数据和研究结果，旨在提出未来跨性别运动员参与女子比赛的科学依据和伦理考量。具体分析了人的生理差异、性别认同及其对体育竞技的影响，同时提及了国际体育组织对相关政策的演变。
  type: document
  format: PDF Document
  size: 852971
  md5: 63997ea948e34e64ba774adf9b3d18c8
  date: '2021-10-06'
  archived: '2024-10-30 06:26:06'
  link: http://cmstykx.cisszgty.com/xhimg/soft/220128/5-22012P93GEN.pdf
  creator: ''
  tags:
  - 跨性别运动员
  - 女子体育比赛
  - 运动员性别检测
  - 伦理学
  - 社会学
  - 科学研究
  - 体育公平
  - 政策分析
  page: 跨性别运动员参加高水平体育比赛的科学思考_page.md
- name: 跳出性别之网
  filename: 跳出性别之网.pdf
  description: 本文讨论了朱迪斯·巴特勒的《消解性别》一书，深入分析其提出的“性别规范”概念及其对性别和身体问题的影响。作者探讨了性别规范的建立如何依赖于社会势力与文化背景，并愈发深入地揭示出性别多样性的被边缘化及其流行性暴力的根源。文章深入分析了巴特勒对性别社会构造、变性手术及其所带来的个体身份认同等多重议题的反思，力图表明性别并非一成不变。文中提及“规范使社会生活得以可能”，提示着我们要关注那些在规范之外的性别表现，进而寻求解放与变革的契机。巴特勒的理论为性别解放和社会转型带来了新的可能性。
  type: document
  format: PDF Document
  size: 343149
  md5: 45d72c881a2411acfad894a7860fd871
  date: 未知
  archived: '2024-10-30 06:26:06'
  link: https://shxyj.ajcass.com/Admin/UploadFile/20130926008/2015-05-26/Issue/ljfpw0em.pdf
  creator: ''
  tags:
  - 性别规范
  - 朱迪斯·巴特勒
  - 消解性别
  - 性别理论
  - 性别多样性
  - 社会公平
  - 文化研究
  - 医学伦理
  page: 跳出性别之网_page.md
- name: 酷儿理论等于同性恋研究吗
  filename: 酷儿理论等于同性恋研究吗.pdf
  description: 本文讨论了酷儿理论与同性恋研究之间的关系。酷儿理论是20世纪90年代兴起于妇女研究领域的后结构主义批判理论，其目标是挑战和解构性别及性取向的传统观念。作者都岚岚通过评述酷儿理论的理论渊源与内涵，探讨了其与同性恋研究之间的差异，并指出国内学界普遍将酷儿理论视为与同性恋研究等同的现象。文章还结合了西方女性主义理论和后结构主义思想，分析了性别和性欲的构成，强调身份的多样性和流动性，呼吁对传统异性恋霸权进行反思与批判，并指出酷儿理论在当代文化研究中的重要性。
  type: document
  format: PDF Document
  size: 293661
  md5: 03868c1971d98df5e704b2d424ed1a6c
  date: 未知
  archived: '2024-10-30 06:38:29'
  link: https://tsla.ecnu.edu.cn/CN/article/downloadArticleFile.do?attachType=PDF&id=529
  creator: ''
  tags:
  - 酷儿理论
  - 同性恋研究
  - 后结构主义
  - 性别研究
  - 性别身份
  - 女性主义
  - 社会批判
  - 文化研究
  page: 酷儿理论等于同性恋研究吗_page.md
- name: 酷儿理论视角下档案与性别身份认同的冲突与和解
  filename: 酷儿理论视角下档案与性别身份认同的冲突与和解.pdf
  description: 本文件探讨了酷儿理论下档案与性别身份认同之间的冲突与和解。酷儿理论认为性别并非自然生成，而是文化和社会构建的结果。文章分析了档案在记录性别身份认同方面的固化局限性与流动性，并从档案与个体/群体的身份认同的关系切入，讨论了档案对性别身份认同的影响及其潜在的构建作用。文件中提到，“档案的历史记录属性与信息相对固化特点及其背后蕴含的权力与权利相互作用，常常使性别身份认同在档案中的实现陷入困境。”此外，档案被看作是一个为性别身份提供常态化机制和发声平台的工具。该研究基于中国知网、万方数据等多种学术资源，尤其关注了性别话语在档案研究中的边缘化问题。
  type: document
  format: PDF Document
  size: 1149761
  md5: 9c0d14e7be113effaae0837e726d9f0f
  date: '2021-06-01'
  archived: '2024-10-30 06:26:06'
  link: https://journal12.magtechjournal.com/Jwk_dax/CN/article/downloadArticleFile.do?attachType=PDF&id=4314
  creator: ''
  tags:
  - 酷儿理论
  - 档案与性别
  - 性别身份认同
  - 性少数群体
  - 社会建构
  - 身份认同
  - 社会权力地方
  page: 酷儿理论视角下档案与性别身份认同的冲突与和解_page.md
subdirs: []
