name: 未知
description: 此目录包含与跨性别主题相关的无法分类的文件
curator: ''
source: ''
tags:
- 教育
- 跨性别
- 教学设计
- 合作协议
- 资源支持
license: ''
files:
- name: 中医精髓图解第二版
  filename: 中医精髓图解第二版.pdf
  description: 《中医精髓图解（第二版）》是一本以图解形式呈现的中医学教材，主编为汤泰元。书中全面介绍了中医学的基础理论，结合现代西医的知识和理论，旨在架起中西医之间的桥梁。书中涵盖阴阳、脏腑、精、神、气、血、津、液等中医核心概念及其在医学上的应用，并通过生动的插图与通俗易懂的文字说明，使得中医理论更加易于理解。该书适合医学专业师生及中医爱好者学习和参考，同时也为推广和现代化中医提供了重要的指导。在书中，作者强调了中医理论的历史背景，对比了中西医在疾病理解与治疗上的异同，并提出了阴阳平衡在健康中的重要性。
  type: document
  format: PDF Document
  size: 8342954
  md5: 4f4ec7d5dc8617cfb6db03ceb007d864
  date: '2008'
  archived: '2024-10-30 06:42:07'
  link: http://www.ecsponline.com/yz/BBA42E8E4C368451AB39A11AB3C5C45C6000.pdf
  creator: ''
  tags:
  - 中医
  - 医学
  - 阴阳理论
  - 脏腑学说
  - 医疗资源
  - 中西医结合
  - 健康生活方式
  page: 中医精髓图解第二版_page.md
- name: 项目名项目合作协议
  filename: 项目名项目合作协议.pdf
  description: 该文件为福建省正荣公益基金会与北京同声异响文化发展有限公司签订的合作协议，主要针对名为“为梦想而战的兄弟”的项目进行资金支持与管理。协议中详细列出了项目的合作内容、资金管理方案、项目进展的监督检查，以及赞助方与承接方的权利和义务。项目旨在通过社群活动提高跨性别兄弟的公众可见度及权利意识，预计受益人数为3000人。项目时间从2021年1月至2021年12月，涉及的资金数额及其使用方式也在协议中有详细说明。此外，文件中还包含了项目的财务管理办法，强调了财务透明化的重要性与相关责任。
  type: document
  format: PDF Document
  size: 370430
  md5: fcddc4a8880b95757340a539023f2345
  date: '2021-01-01'
  archived: '2024-10-30 06:35:16'
  link: http://www.zrgy.org/upload/2021/16213232955420316.pdf
  creator: ''
  tags:
  - 跨性别
  - 项目合作
  - 公益基金会
  - 资金管理
  - 兄弟社群
  - 社会支持
  page: 项目名项目合作协议_page.md
subdirs: []
