name: 法律评论与文献
description: 本目录包含有关跨性别人士的法律评论与研究文献，探讨代孕、婚姻权利、变性法律等相关法律问题，旨在推进对变性人权利的理解与保护。
curator: ''
source: ''
tags:
- 法律
- 变性人
- 婚姻法
- 生命伦理
- 法律评论
- 社会政策
- 性别认同
license: ''
files:
- name: 上政法律評論
  filename: 上政法律評論.pdf
  description: 本文收录了《上政法律评论》2016年第4期中的多篇法律文章，重点讨论了中国法律体系中的一些重要问题，包括对管制刑的改革建议、禁止双重危险原则的新发展及其对我国刑事诉讼法的启示，并探讨了《刑法修正案（九）》在去性别化方面的必要性。这些文章涉及法律、法学理论及其在实践中的应用，旨在推动中国法治发展和完善。具体包括对管制刑与缓刑之间的比较，探讨了两者在法律适用上的差异与重要性，并提出用缓刑替代管制刑的建议。而对于禁止双重危险原则的讨论，则涉及到国际法的变化和中国刑事诉讼法的改革方向，强调应对现代法治环境的适应与转变。
  type: document
  format: PDF Document
  size: 1481182
  md5: 2c7180f5977929f0a40d52a67692ccb6
  date: 2016年
  archived: '2024-11-01 19:00:34'
  link: https://www.shupl.edu.cn/_upload/article/files/43/e0/fb2612754677bd36720905285387/0442f442-40e0-4dd8-95e7-7b7f42e0aa8b.pdf
  creator: ''
  tags:
  - 法律评论
  - 管制刑
  - 缓刑
  - 禁止双重危险原则
  - 刑法修正案
  - 去性别化
  - 刑事诉讼法
  page: 上政法律評論_page.md
- name: 从刻板印象到关系型歧视
  filename: 从刻板印象到关系型歧视.pdf
  description: 本文件是关于性少数群体在就业市场上遭受歧视的问题，主要探讨了美国法律在此领域的发展历程，尤其是通过性别刻板印象理论与关系型歧视的概念对就业歧视的理解和适用。文章分析了美国联邦法院关于性少数群体的就业歧视诉讼，如何从原有的性别歧视的窄义理解逐步扩展到涵盖性取向和性别认同的广义理解。本文认为虽然中国与美国的法律背景和社会环境差异很大，但在反就业歧视的立法理念上却有相似之处，强调以绩效为基础的职场治则。文件中提到的理论为中国提升性少数群体的权益保护提供了借鉴，包括劳动法第七章的相关内容及反就业歧视的潜在法律基础。
  type: document
  format: PDF Document
  size: 1653583
  md5: aa6fedd94a7b163d1286943917cc700b
  date: '2019-06-01'
  archived: '2024-10-30 06:37:16'
  link: http://journal.pkulaw.cn/PDFFiles/%E4%BB%8E%E2%80%9C%E5%88%BB%E6%9D%BF%E5%8D%B0%E8%B1%A1%E2%80%9D%E5%88%B0%E2%80%9C%E5%85%B3%E7%B3%BB%E5%9E%8B%E6%AD%A7%E8%A7%86%E2%80%9D.pdf
  creator: ''
  tags:
  - 就业歧视
  - 性少数群体
  - 法律政策
  - 性别刻板印象
  - 关系型歧视
  - 中国法律
  - 平等就业权
  page: 从刻板印象到关系型歧视_page.md
- name: 关于代孕爸爸事件的生命伦理与法律问题思考
  filename: 关于代孕爸爸事件的生命伦理与法律问题思考.pdf
  description: 本文件为《医学与哲学（人文社会医学版）》2008年10月第29卷第10期的论文，作者邹涛，标题为《关于“代孕爸爸”事件的生命伦理与法律问题思考》。论文详细探讨了全球第一位“代孕爸爸”托马斯·比提一事所引发的生命伦理与法律问题。文件中提到，托马斯在进行变性手术后，选择成为代孕父亲，旨在通过这一过程引发的伦理和法律讨论，以重新审视变性人婚姻、人工辅助生殖技术和代孕等新兴生命技术的合理性与潜在风险。文章深入分析了生殖健康与权利、法律身份、胎儿权利等层面的问题，并强调制定合理的法规以防止伦理和社会混乱的重要性。
  type: document
  format: PDF Document
  size: 98778
  md5: d1ebfa6d55a58dd502ae44e49fcaaa6b
  date: '2008-10-01'
  archived: '2024-11-01 19:00:35'
  link: https://yizhe.dmu.edu.cn/data/article/yxyzx/preview/pdf/2008-10A-9.pdf
  creator: ''
  tags:
  - 代孕
  - 生命伦理
  - 法律问题
  - 变性人
  - 生殖权利
  - 医学与哲学
  - 托马斯·比提
  page: 关于代孕爸爸事件的生命伦理与法律问题思考_page.md
- name: 变性人、劳教者、在校大学生等今天起可登记结婚
  filename: 变性人、劳教者、在校大学生等今天起可登记结婚.pdf
  description: 本文件是关于新的《婚姻登记条例》的新闻报道，日期为2003年10月1日。根据条例，变性人、劳教人员和在校大学生等群体可以登记结婚，简化了结婚和离婚手续，取消了之前的强制性婚检和介绍信要求。文件中详细描述了新的条例实施引发的社会反响，包括婚姻登记处的咨询电话剧增、登记人数锐减等情况。记者还特别强调，变性人只要经过变性手术，并按新的性别办理身份证，就可以合法注册结婚。此外，还提到新条例的实施可能导致国庆期间登记结婚的人数激增，这标志着对跨性别者在婚姻法律框架下权利的进一步认可。
  type: document
  format: PDF Document
  size: 628921
  md5: 05f16783fc1cb3c7c21d8e2da1ea81ec
  date: 2003年10月01日
  archived: '2024-10-30 15:43:34'
  link: ''
  creator: ''
  tags:
  - 婚姻登记条例
  - 跨性别者
  - 法律政策
  - 社会新闻
  - 变性人
  - 婚姻手续
  page: 变性人、劳教者、在校大学生等今天起可登记结婚_page.md
- name: 变性人可否结婚
  filename: 变性人可否结婚.pdf
  description: 该文件是一篇关于变性人婚姻法律地位的讨论文章，来源于广西政法报，发表于2003年1月17日。文章通过一个来自桂林的读者来电案例提出了具体问题：变性人在经历变性手术后是否有权结婚。律师解答了这个问题，强调法律上并没有明确规定禁止变性人结婚，只要变性人拥有合法的医院证明并完成相关的性别变更登记，就可以享有与常人相同的婚姻权利。同时，文章提及《婚姻法》关于婚姻自由及一夫一妻制的相关条款，指明法律应当平等对待变性人，不得干涉其婚姻自由。这篇文件反映了2003年中国法律对于变性人的婚姻权益的认识，具有重要的法律和社会意义。
  type: document
  format: PDF Document
  size: 54480
  md5: 5845eb8bbb472ff1c41f80d287660a81
  date: '2003-01-17'
  archived: '2024-10-30 15:44:34'
  link: ''
  creator: ''
  tags:
  - 变性人
  - 婚姻法律
  - 婚姻平等
  - 性别认同
  - 法律权利
  - 社会环境
  - 广西政法报
  page: 变性人可否结婚_page.md
- name: 变性人户口被许可易性的法律意义_本报记者_李青
  filename: 变性人户口被许可易性的法律意义_本报记者_李青.pdf
  description: 本文件为2008年12月4日《法制日报》的一篇报道，由记者李青撰写，主要探讨了江西省出台的变性人户口变更政策及其法律意义。文章指出，目前中国法律对变性手术没有明确支持，也不承认心理性别，造成了变性人面临法律上的空白和困境。报道强调，变性人在手术后往往处于一种"真空无性别状态"，并无法更改户口、身份证等法律文件，进而影响其生活。江西省公安厅的规定允许变性人在完成手术后依法变更户口性别，为变性人群体提供了法律支持，展示了社会对这一群体的关怀。文章还详细描述了部分变性人在此法律实施前后的亲身经历，表达了法律变化对他们生活的重要影响。
  type: document
  format: PDF Document
  size: 21437
  md5: e058de62be115bc24b3876dc299d4012
  date: '2008-12-04'
  archived: '2024-10-30 15:44:52'
  link: ''
  creator: ''
  tags:
  - 跨性别
  - 变性人
  - 法律政策
  - 户口变更
  - 社会关怀
  - 心理性别
  - 生存现状
  page: 变性人户口被许可易性的法律意义_本报记者_李青_page.md
- name: 构筑弹性的《婚姻法》调适变性伦理_特约评论员_杜宇
  filename: 构筑弹性的《婚姻法》调适变性伦理_特约评论员_杜宇.pdf
  description: 该文件为特约评论员杜宇撰写的时论文章，探讨了中国《婚姻法》在调整变性伦理方面的弹性和适应性。文章首先回顾了卫生部发布的《变性手术技术管理规范（试行）》，指出其对变性手术申请者提出的条件。文件讨论了当前法律对变性人群的认知及其对婚姻状态的影响，特别提到‘未在婚姻状态’这一条款如何影响变性者的权利。同时，文章还提及了中国的婚姻法在性别变化方面的不足与紧迫性，建议立法确认变性身份并完善相关法律，保障变性人在法律上的权益和地位，尤其是在婚姻中的合法权益。最后，作者呼吁社会对变性问题的理解与支持，以促进开放与包容的社会环境。
  type: document
  format: PDF Document
  size: 22098
  md5: c6f263e699ce769269a20e0cf38a9be2
  date: '2009-11-25'
  archived: '2024-10-30 15:43:17'
  link: ''
  creator: ''
  tags:
  - 变性人权利
  - 婚姻法
  - 变性手术
  - 法律政策
  - 伦理问题
  - 中国社会
  - 性别认同
  - 社会环境
  page: 构筑弹性的《婚姻法》调适变性伦理_特约评论员_杜宇_page.md
- name: 法律对“变性”的回应_《我国现行法律中性法律的理论与现实盲点研究》课题组
  filename: 法律对“变性”的回应_《我国现行法律中性法律的理论与现实盲点研究》课题组.pdf
  description: 本文件为《我国现行法律中性法律的理论与现实盲点研究》课题组所作的研究成果，探讨了在中国法律体系中对变性现象的回应和相关法律空白。文章指出，变性作为一个新兴社会现象，在缺乏相应法律的情况下，变性主体的权益得不到保护，导致法律关系混乱。文中详细分析了变性手术的前置条件及法律程序，并讨论了婚姻法、继承法和刑法等与变性相关的法律条款，以及如何改善现有法律以保障变性人的权益。建议通过明确的法律规定、严格的医疗鉴定和保密责任来规范变性手术，同时呼吁引入相应的法律保护，以防止滥用权利和保证变性人权利的实现。
  type: document
  format: PDF Document
  size: 274601
  md5: 9f8bb50b7825564a97ec99f3b2c5c540
  date: '2008-01-01'
  archived: '2024-10-30 15:44:05'
  link: ''
  creator: ''
  tags:
  - 变性
  - 法律
  - 权益保护
  - 医疗规范
  - 婚姻法
  - 继承法
  - 社会现象
  - 性别法律
  page: 法律对“变性”的回应_《我国现行法律中性法律的理论与现实盲点研究》课题组_page.md
- name: 罪犯变性了怎么办_贾振华
  filename: 罪犯变性了怎么办_贾振华.pdf
  description: 本文件名为《罪犯变性了怎么办》，由贾振华撰写，讨论了变性人所面临的法律问题与社会观念。随着社会对变性手术接受度的提升，越来越多的人选择变性，随之而来的法律问题和社会视角的变化引发关注。文件中提到，变性人一般需要通过医学鉴定获得性别身份的法律认可，但该过程充满困难。在某些司法案例中，判决的依据多依赖生物学因素，这对变性人申请法律身份的认定造成了不小的挑战。同时，文章提到了一些国家在变性合法性方面的进步，例如允许变性人更改身份证明，但仍有一些情况下法律保护不足，导致变性人面临逃避责任的争议。
  type: document
  format: PDF Document
  size: 512066
  md5: abba31a8d03987c51e26191c30978bb1
  date: 未知
  archived: '2024-10-30 15:44:58'
  link: ''
  creator: ''
  tags:
  - 变性
  - 法律问题
  - 性别身份
  - 变性人
  - 医学鉴定
  - 社会观念
  page: 罪犯变性了怎么办_贾振华_page.md
- name: 西方国家变性人越来越多众法官束手无策_齐书学
  filename: 西方国家变性人越来越多众法官束手无策_齐书学.pdf
  description: 本文档讨论了西方国家变性现象的增长及其对法律系统的影响。随着整形外科学的发展，通过手术实现变性的变性人数不断增加，法律面临着传统观念与新兴现实之间的冲突。文件中详细探讨了一系列关于变性人法律地位和权利的问题，例如变性人的婚姻权利、儿童抚养权、兵役问题等。文中提到许多变性案件在法院审理中面临着激烈的辩论和不确定的判决，尤其是在缺乏明确法律规定的情况下。具体案例包括西班牙安东尼奥·卡斯蒂略的案件，其变性后的权益申请在法律上遭遇困难。这些情况揭示了当前法律体系在适应变性人权益上所面临的挑战。
  type: document
  format: PDF Document
  size: 200720
  md5: bcd255f7cb3c8a21999a993370bb9803
  date: 未知
  archived: '2024-10-30 15:45:04'
  link: ''
  creator: ''
  tags:
  - 变性人
  - 法律问题
  - 性别认同
  - 西方国家
  - 法律改革
  - 社会现象
  - 案例研究
  page: 西方国家变性人越来越多众法官束手无策_齐书学_page.md
- name: 论变性人的性别判定——附一例变性人离婚案件报告_潘永久
  filename: 论变性人的性别判定——附一例变性人离婚案件报告_潘永久.pdf
  description: 本文为第五次全国法医学术交流会的论文集中的一篇，主要讨论了变性人在法律性别判定中的问题。文章分析了变性手术的医学背景、过程及其对伤残评定的影响，指出变性人在法律上性别身份的判定远不止于生理特点，同时强调社会性别的重要性。文中提到‘法律性别’这一概念，主张通过立法形式明确变性人手术后的法律身份，确保他们在法律上享有合适的权利和义务。文件还详细报告了一例女性变性为男性后与另一女子结婚并诉讼离婚的案例，探讨了这一过程中涉及的法律争执及变性人的性别认定问题。
  type: document
  format: PDF Document
  size: 169620
  md5: b82993e0178320ac7d8c8440ec2f2500
  date: 未知
  archived: '2024-10-30 15:47:00'
  link: ''
  creator: ''
  tags:
  - 变性人
  - 法律性别判定
  - 伤残评定
  - 变性手术
  - 性别认同
  - 离婚案件
  - 社会性别
  - 法律政策
  page: 论变性人的性别判定——附一例变性人离婚案件报告_潘永久_page.md
- name: 论建立变性人婚姻家庭之特别制度_王正苍
  filename: 论建立变性人婚姻家庭之特别制度_王正苍.pdf
  description: 本文由王正苍撰写，探讨了关于为变性人建立婚姻家庭特别制度的法律思考。文章首先分析了变性人在婚姻法中的地位，指出我国现行法律对变性人的特殊婚姻权利尚未作出明确规定，变性人能够依靠何种标准来确认自己的婚姻能力。文章讨论了变性人在不同国家和地区如何通过法律程序确认性别身份，以及法律上对变性人婚姻的承认与规定。文中提到，不同国家在对变性人婚姻的法律适用上存在差异，例如某些国家已允许变性人根据变更后的性别结婚，而我国的法律体系仍需进一步完善和适应变性人的需求。此外，文章还探讨了变性人收养和人工生育子女的法律问题，认为变性人的婚姻及家庭问题在法律上应给予更多的关注与保障。总之，文章呼吁对变性人婚姻家庭的特别制度进行立法思考，以保护变性人的合法权益，并推动社会对变性人群体的理解与接受。
  type: document
  format: PDF Document
  size: 253933
  md5: 4c9e4aa1158569743091ab73aa5f54f0
  date: 未知
  archived: '2024-10-30 15:46:48'
  link: ''
  creator: ''
  tags:
  - 变性人
  - 婚姻法
  - 法律制度
  - 家庭关系
  - 性别认同
  - 婚姻权利
  - 法律保障
  - 社会政策
  page: 论建立变性人婚姻家庭之特别制度_王正苍_page.md
subdirs: []
