name: 其他
description: 本目录收录了与法律法规相关的跨性别话题，特别是关于反就业歧视的比较研究，探讨英国的相关法律与我国法律的对比及改进的可能性，旨在提升对跨性别权益的重视和理解。
curator: ''
source: ''
tags:
- 法律政策
- 反就业歧视
- 跨性别权益
- 比较研究
- 中国法律
license: ''
files:
- name: 2022_世界艾滋病大会强调科学创新与合作吉利德为终结HIV_全球
  filename: 2022_世界艾滋病大会强调科学创新与合作吉利德为终结HIV_全球.pdf
  description: 该文件是关于2022年世界艾滋病大会的新闻稿，强调了科学创新与合作在终结HIV全球流行中的重要性。文件中提及吉利德科学公司在会议中的角色和贡献，公开了该公司在HIV临床研发领域的重要项目及其推动健康平等的承诺。会议将于2022年7月29日至8月2日召开，吉利德科学将在会上分享其在HIV治疗、预防和治愈方面最新的科研数据及研发项目，包括对初治HIV感染者的治疗方案、研究数据及相关社区合作的内容。
  type: document
  format: PDF Document
  size: 214303
  md5: 2fa6eb2989b4d2d26e0f8e47fd4dfbc2
  date: '2022-07-21'
  archived: '2024-11-01 09:18:14'
  link: https://www.gileadchina.cn/-/media/gilead-china/pdfs/news-and-press/press-releases/20220722-cn.pdf
  creator: ''
  tags:
  - 艾滋病大会
  - HIV治疗
  - 科学创新
  - 吉利德科学
  - 医疗资源
  - 公共卫生
  - 跨性别健康
  page: 2022_世界艾滋病大会强调科学创新与合作吉利德为终结HIV_全球_page.md
- name: 实施变性手术应以法定程序的审理为前提_汤啸天
  filename: 实施变性手术应以法定程序的审理为前提_汤啸天.pdf
  description: 本文探讨了变性手术的法律和社会问题，强调实施变性手术应以法定程序的审理为前提。作者汤啸天指出，虽然近年来在尊重人权和理解弱势群体方面有了积极进展，但我国对变性手术的相关法律法规仍然缺失。文章论述了变性手术可能引发的法律纠纷及患者在手术后的心理变化，提到相应的法律、社会、伦理问题应得到妥善处理。此外，文中总结了现行医疗机构在施行变性手术时面临的挑战，包括对健康器官的合法性、手术后的生理和心理适应，以及性别变更对亲属关系带来的影响，最后呼吁建立更加严格的法律框架来管理变性手术的实施。
  type: document
  format: PDF Document
  size: 1082794
  md5: 7b585517f8a86d0d5f5a7b1122e775d0
  date: 未知
  archived: '2024-10-30 15:49:36'
  link: ''
  creator: ''
  tags:
  - 变性手术
  - 法律问题
  - 人权
  - 易性癖
  - 社会伦理
  - 医疗资源
  - 亲属关系
  - 手术风险
  page: 实施变性手术应以法定程序的审理为前提_汤啸天_page.md
- name: 经济与法律学院
  filename: 经济与法律学院.pdf
  description: 该文件来自辽宁科技大学经济与法律学院，内容涉及学术报告会的几位主讲人的研究主题。特别值得注意的是，赫宇彤的研究主题为《跨性别劳动者的平等就业权》，探讨了在法律框架内跨性别者面临的就业歧视问题，并提出可能的法律解决措施。其他主讲人则研究了各类法律与社会问题，包括知识产权、环境保护法等，这些研究反映了学术界对多元化性别和法治建设的持续关注。
  type: document
  format: PDF Document
  size: 8839718
  md5: ec93f3c177e89a217219dc47c0340bea
  date: 未知
  archived: '2024-11-01 09:20:59'
  link: https://www.ustl.edu.cn/__local/E/C9/3F/3C177E89A217219DC47C0340BEA_3371D018_86E226.pdf
  creator: ''
  tags:
  - 跨性别
  - 劳动者平等权
  - 法律研究
  - 经济与法律学院
  - 学术报告
  - 环境保护法
  page: 经济与法律学院_page.md
- name: 英国反就业歧视法与我国立法之完善
  filename: 英国反就业歧视法与我国立法之完善.pdf
  description: 该文件为《英国反就业歧视法与我国立法之完善》的PDF文档，旨在比较和分析英国法律如何保护跨性别者免受就业歧视，以及如何改进我国的相关立法，以更好地保障跨性别者的权益。虽然无法从PDF中提取具体文本内容，但可以推测该文档可能探讨了英国反就业歧视法的条款、实施效果及对跨性别者的影响，同时也可能提出了针对我国法律现状的建议和改善方案。文中可能涉及现实生活中跨性别者在就业中的面临的歧视情况及相应的法律保障。
  type: document
  format: PDF Document
  size: 162
  md5: bc56979a0b381a791dd59713198a87fb
  date: 未知
  archived: '2024-10-30 07:11:55'
  link: http://iolaw.cssn.cn/zzwx/201905/P020190522400944034955.pdf
  creator: ''
  tags:
  - 法律政策
  - 就业歧视
  - 跨性别权益
  - 比较法
  - 社会保障
  page: 英国反就业歧视法与我国立法之完善_page.md
subdirs: []
